.gitignore
requirements.txt
tests/test_url_safe_tokens.py
utils/url_safe_token.py

- generate_token(payload, secret, salt): generates an encrypted url token for the payload, using the secret key and salt passed in.
- check_token(token_secret, salt, max_age_seconds): decrypts the payload using the secret key and salt. Throws SignatureExpired exception if the token is older than the now + max_age_seconds.

Created url_safe_token modules.

---

notifications_utils/template.py

Use one liner `if` statement

---

tests/test_recipient_validation.py

Added another use case for international numbers. Actually test those numbers in the unit test.

Small tweak to unit test

---

Makefile
README.md

Partly addresses: https://github.com/alphagov/notifications-manuals/issues/9
Please see the commit messages for more details.

Simplify README and standardise tasks

---

notifications_utils/polygons.py

Our polygon smoothing works by expanding and then contracting each shape.
Because it was using different parameters (resolution and join style) for the expansion and contraction it was introducing artefacts, i.e. it was creating entirely new shapes. This seemed to be mostly happening when the original polygons were very small, like those used by the Flood Warning Service.
This commit refactors the smoothing to re-use our existing `bleed_by` method to expand and contract the polygon. By re-using this method we have the same parameters for both the expansion and contraction. This seems to prevent the artefacts.
Note the artefacts around the centre of Penzance and St Michael’s Mount
Original | Before | After
---|---|---
```shell
python -m timeit -s "from notifications_utils.polygons import …
```

Refactor smoothing for reuse and fewer artefacts

---

CHANGELOG.md
notifications_utils/formatters.py

See commit messages for further details

Small tidy up - add changelog and remove unused variable

---

MANIFEST.in
notifications_utils/polygons.py
setup.cfg

Details in the commit messages.

Fix a couple of warnings and run more flake8-bugbear checks

---

notifications_utils/version.py
setup.py

fixes https://github.com/py-pdf/PyPDF2/security/advisories/GHSA-xcjx-m2pj-8g79

Bump pypdf2 to 1.27.5

---

CHANGELOG.md
notifications_utils/version.py
notifications_utils/version_tools.py
scripts/bump_version.py

Create a `make` command like this in any app:
```makefile
.PHONY: bump-utils
bump-utils:  # Bump notifications-utils package to latest version
${PYTHON_EXECUTABLE_PREFIX}python -c "from notifications_utils.version_tools import upgrade_version; upgrade_version()"
```
To get:

Add script to update apps to latest version

---

CHANGELOG.md
notifications_utils/letter_timings.py
notifications_utils/version.py
tests/test_letter_timings.py

This will let apps:
- work out whether a day is a working day
- get the previous working day for a given day (to match the existing function for getting the next working day)

Add some more help functions to `letter_timings`

---

notifications_utils/logging.py
notifications_utils/version.py
tests/test_logging.py

This will allow us to inject custom log attributes based on the app.
We also add a new centralised UserIdFilter

Allow apps to pass extra logging filters

---

notifications_utils/jinja_templates/letter_image_template.jinja2
notifications_utils/version.py
tests/test_template_types.py

Didn’t account for a one-pager, where the single page is both the first and last page of the letter.

Fix bug with `page--first` and `page--last` classes

---

CHANGELOG.md

Add note to changelog for v65.2.0

---

CHANGELOG.md
notifications_utils/field.py
notifications_utils/insensitive_dict.py
notifications_utils/markdown.py
notifications_utils/recipients.py
notifications_utils/template_change.py
notifications_utils/version.py
requirements_for_test.txt
setup.py
tests/test_recipient_csv.py
tests/test_serialised_model.py
tests/test_template_types.py

This pull request means the package can be installed in a Python 3.11 or Python 3.12 environment.
See individual commits for detail.

Make package compatible with Python 3.11 and 3.12

---

CHANGELOG.md
notifications_utils/clients/antivirus/antivirus_client.py
notifications_utils/clients/zendesk/zendesk_client.py
notifications_utils/version.py
scripts/bump_version.py
setup.py

* reuse requests sessions (for small perf boosts)
* remove unused subdependency geojson
* fix the version bump script in case you ever ran `pip install -e .` or similar in your venv

A couple of QoL changes

---

CHANGELOG.md
notifications_utils/clients/antivirus/antivirus_client.py
notifications_utils/clients/zendesk/zendesk_client.py
notifications_utils/version.py

- Revert "reuse a requests session for requests to the same host"
- Bump and document version
https://gds.slack.com/archives/C010BPLQ4CE/p1704374630059149

Revert single session for client requests

---

notifications_utils/sanitise_text.py
notifications_utils/version.py
tests/test_sanitise_text.py

add polish unicode decompositions

Support polish in GSM

---

notifications_utils/version.py

I didn't run make patch-version until after it was merged....
Fixing this now.

Forgot to bump version number for crown

---

.gitignore
Makefile
requirements_for_test.txt

add make watch-tests command

---

CHANGELOG.md
notifications_utils/celery.py
notifications_utils/version.py

This is to allow me to better analyze performance and confirm or dispel some hunches I have.

NotifyTask: include pid and other structured fields in completion logs

---

CHANGELOG.md

added missing changelog for 81.1.1

---

CHANGELOG.md
notifications_utils/version.py
requirements_for_test.txt
setup.py

Fixes https://github.com/advisories/GHSA-cpwx-vrp4-4pq7

Bump `jinja2` to 3.1.6

---

CHANGELOG.md
notifications_utils/template.py
notifications_utils/version.py
notifications_utils/version_tools/.pre-commit-config.yaml
notifications_utils/version_tools/requirements_for_test_common.in
requirements_for_test.txt

Bug fixes, new rules and performance improvements:
https://github.com/astral-sh/ruff/blob/3150812ac4cf8fbd852a445d6467cf641f736b65/CHANGELOG.md#0114

Bump ruff to 0.11.4
