notifications_utils/logging.py

- Usage:
in Flask application pass an initialized statsd client into the logger.
only the API does this now.
then setup the data required for the after_request hook
@app.before_request
def record_start_time():
g.start = monotonic()
g.endpoint = request.endpoint
this records the start time and the endpoint (module and method) that the request will invoke.
The logger will then use these to create statsd metrics to record the event (count) and the time taken

Added statsd logging into the after_request handler

---

notifications_utils/template.py

So there’s less logic in the `Template`’s `__init__` method.

Refactor renderer into a getter/setter

---

README.md
requirements_for_test.txt
scripts/run_tests.sh
setup.cfg

PEP8 was renamed to pycodestyle; this issue explains why: PyCQA/pycodestyle#466
This commit changes our tests to use pycodestyle instead of pep8.
No changes to our code were required as a result.

Use pycodestyle instead of PEP8

---

setup.cfg

if a `pytest.mark.xfail` passes when you expect it to fail:
```
=================== 571 passed, 16 xfailed, 3 xpassed in 6.48 seconds ===================
Unit tests passed
```
```======================================= FAILURES =======================================
_________________ test_phone_number_accepts_valid_values[07123456789] __________________
[XPASS(strict)]
__________ test_valid_phone_number_can_be_formatted_consistently[07123456789] __________
[XPASS(strict)]
____________ test_validates_against_whitelist_of_phone_numbers[07123456789] ____________
[XPASS(strict)]
=================== 3 failed, 571 passed, 16 xfailed in 6.39 seconds ===================
Unit tests failed
```

make xpass fail the test run

---

notifications_utils/logging.py
tests/test_request_id.py

The info level logging was logging the body of a file that was uploaded to S3, which is naughty.
BTW: I didn't bump the version number because 15.0.4 is yet to be used in admin and api.

Configure the boto3 logging to WARNING level.

---

notifications_utils/template.py
tests/test_template_types.py

Situation
---
A CSV file has an optional address column (eg `address line 3`) but no values for this column in (some of) the rows.
Problem
---
The outputted data for those rows will have `<span class='placeholder'>…` in the address block, instead of empty strings.
Why it’s happening
---
`{'x': None}.get('x', '')` returns `None`, _not_ `''`.
`Field`s treat `None` as missing personalisation, and `''` as a valid replacement. So they were seeing missing personalisation when the intent of the code was to say _replace this bit of the address with an empty string because it’s optional_.
The fix
---
Converting `None` to `''` for all optional address lines (fix is in 01bd264, other commit is just whitespace changes).

Fix empty address placeholders becoming HTML

---

notifications_utils/field.py
notifications_utils/formatters.py
notifications_utils/template.py
tests/test_formatters.py
tests/test_template_types.py

We have a problem where stuff like `&amp;` was showing up in our letters. We shouldn’t be doing this sanitising in the data we send to DVLA, but we also shouldn’t be letting users pass DVLA-markup like `<cr>` through us.

Don’t escape HTML in the data we output to DVLA

---

notifications_utils/international_billing_rates.py
notifications_utils/recipients.py
tests/test_international_billing_rates.py
tests/test_recipient_validation.py

This pull request adds validation that can be optionally enabled to allow international phone numbers. We consider an international phone number to be anything that starts with:
- `00` (but not `0`), and then a valid country prefix
- `+` and then a valid country prefix
- just a valid country prefix
As with UK numbers we ignore any brackets, dashes, spaces before validating.
There is one exception, Russia, whose country prefix is `7`. A number starting with `7` could be either a UK mobile number or a Russian phone number. So we only consider a phone number to be Russian if the part after the `7` is at least 10 digits.
Any number that starts with `7` and has fewer than 10 digits we treat as a UK mobile number. UK mobile numbers have 9 digits after the first `7`.
This pull request also does …

Validate international phone numbers

---

notifications_utils/international_billing_rates.py
notifications_utils/recipients.py
tests/test_recipient_validation.py

The API needs to know three things about a phone number:
- whether it’s international
- what the prefix is
- how many billable unit to charge for a text sent to this number
This commit adds a function to return a tuple of that information.
This only subtlety is what to do with a number like `1664000000000`, which matches USA (`1`) and Montserrat (`1664`). In this case we return the most precise match, ie Montserrat.

Add function to return info about a phone number

---

notifications_utils/formatters.py
notifications_utils/template.py
tests/test_formatters.py
tests/test_template_types.py

Turns out that Mistune has an option to respect single newlines like Github-flavored markdown does. This is much cleaner than our hacky thing of adding two spaces before a single newline to force the Markdown parser to see it.

Use Mistune’s built in newline handling

---

tests/test_recipient_validation.py

Makes sure we don’t enable the behaviour described in this issue: https://github.com/alphagov/notifications-admin/issues/1369

Make sure we reject email addresses with pipes

---

notifications_utils/formatters.py
tests/test_formatters.py

Markdown requires you to do lists like this:
> * apple
> * orange
>
> 1. Banana
> 2. Paw-paw
Users that aren’t familiar with Markdown often don’t realise that the space between the bullet or number and the text of their list item is significant – and why should they? Let’s allow them to also do:
> *apple
> *orange
>
> 1.banana
> 2.paw-paw
This commit:
1. copies the regexes used by our Markdown parser
2. modifies them to not require the space
3. overrides the parser’s regexes with the modified ones
The original regexes can be found here – only difference is removing the (literal) space character from them:
https://github.com/lepture/mistune/blob/5b8c3f7db4321bada0b955a9fb833a3faba4a67f/mistune.py#L118-L138

Don’t require space between asterisk and list item

---

notifications_utils/formatters.py
notifications_utils/template.py
tests/test_formatters.py
tests/test_template_types.py

I’ve seen a couple of times (and we’ve done it in emails our service has sent) where a space sneaks in before a comma. This tends to happen with placeholders, eg:
> Hi ((name)) ,
…which results in:
…which doesn’t look great.
Now we could do some postprocessing of the template content to remove whitespace between closing placeholder tags and commas, ie look for anything like `)) ,` and strip it before saving the template.
I think it’s better to do it at the time of rendering because:
- this covers templates already in the system
- I can’t think of a single case where we’d _ever_ want a space before a comma (butt in here if you can)
So this commit does the replacement in all the places where it might be useful, for all types of messages.
The tests are fairly verbose here, but this stuff is …

Remove whitespace before commas in things we send

---

tests/test_template_types.py

We don’t care how many times these mocks are called. Just that they’re called at least once for the template subject and content.

Make tests less dependent on implementation

---

.flake8
notifications_utils/logging.py
notifications_utils/recipients.py
notifications_utils/s3.py
notifications_utils/timezones.py
requirements_for_test.txt
scripts/run_tests.sh
setup.cfg
tests/test_base_template.py
tests/test_logging.py
tests/test_recipient_csv.py
tests/test_recipient_validation.py
tests/test_redis_client.py
tests/test_template_types.py

[The GDS Way™](https://gds-way.cloudapps.digital/manuals/programming-languages/python/linting.html#how-to-use-flake8) recommends using [Flake8](http://flake8.pycqa.org/en/latest/) to lint Python projects.
This commit takes the Flake8 config [from Digital Marketplace API](https://github.com/alphagov/digitalmarketplace-api/blob/d5ab8afef4a0472f9d266d94ab4ffe1333a9aaad/.flake8) and removes the bits we don’t need.
It changes the `max_complexity` setting to 8, which is the most complex code we have in this repo currently (we shouldn’t be writing code _more_ complex than what we already have).
This commit also fixes the errors found by Flake8, which includes 6(!) tests which were never getting run because they had the same names as existing tests.
Here is a full list of the errors that were …

Add Flake8 linting to project

---

notifications_utils/field.py
requirements_for_test.txt
scripts/run_tests.sh
tests/test_field.py
tests/test_field_html_handling.py
tests/test_international_billing_rates.py
tests/test_placeholders.py

No actual logic change here, but lots of refactoring.
* Tests run sequentially.
* Placeholders with `??` in the middle are known as optional placeholders in code
* In the `Field` class, a regex matched placeholders by `((.*))`, but also at the same time identified whether it was a conditional 
* Tests run in parallel
* Placeholders with `??` in the middle are known as _conditional_ placeholders.
* In the `Field` class, a regex matches anything with `((.*))` as some sort of placeholder
* A new `Placeholder` class handles extracting the name, and working out if it's conditional
- in the future, this class will also handle if placeholders are optional too

Refactor placeholder code

---

notifications_utils/recipients.py
tests/test_recipient_csv.py

The underlying CSV file never changes once the class has been instantiated – i.e. we never reuse an instance of the `RecipientCSV` class with a different file.
Therefore we should never read from the file more than once.
This will allow us to do some things which previously would have been very inefficient, for example:
Looping through all preceding rows every time you want one row is very inefficient – basically an example of [Shlemiel the painter’s algorithm](https://www.joelonsoftware.com/2001/12/11/back-to-basics/).
Since the rows are now a list, not a generator, we can index directly into them.

Make looking up individual CSV rows faster

---

notifications_utils/jinja_templates/email_template.jinja2
tests/test_template_types.py

One of our users (using Outlook 2016 on Windows 10) reported issues with the top banner of our email template when set up with their branding:
- the spacing between the brand image and text was missing
- the column of the main content area was a lot larger than that for the banner
We have been unable to replicate this when testing with Email on Acid. The problems described can be seen with other combinations of email client and OS though. These fixes work on those versions (and don't break any existing code) so it's worth deploying them to see if they have an effect for this user.
The fixes are:
- replacing the padding and margin between the brand image and text with a spacer cell/image combo
- making higher DPI systems pick up our width styles by duplicating those set in HTML attributes …

Add Microsort-specific spacing styles

---

tests/test_formatters.py

So we don’t accidentally break people’s templates.

Test for headings with an without spaces before the octothorp

---

notifications_utils/formatters.py
tests/test_template_types.py

Currently our preheader renders links the same way as a plain text email does (i.e. by printing the URL after the link text).
This isn’t an accurate preview. The person opening the email won’t see the URL, they’ll only see the link text.
So this commit removes the URLs from the preheader, but keeps the text of the link.

Don’t include URLs in the preheader

---

notifications_utils/clients/statsd/statsd_client.py
setup.py

- The statsd client uses UDP which means it doesn't know when the IP
address it is sending to has disappeared
- We would like to run the statsd exporter on the PaaS so that we can
co-locate it, scale it, monitor it easily etc. When the exporter gets
redeployed on PaaS or PaaS have to re-run it, its IP address changes and
the statsd clients in the apps sends the metrics into the void
- This ones uses socket.sendto(address) so should re-resolve DNS on each
packet
- The DNS it is resolving is BOSH DNS which is very quick so this
shouldn't affect the performance much

REP-340: Use a different statsd client

---

tests/test_recipient_csv.py

This is a question we had while debugging something. Realised there wasn’t a test that used `.get_rows()` in a job in the same way that the API does.

Add test that simulates processing a big job

---

notifications_utils/template.py

We used to raise these exceptions when some of the placeholders for a template were missing. We don’t signal this by raising exceptions any more.

Remove unused exceptions

---

Makefile

Allow developers to create their virtualenvs outside of the makefile
like they already do using virtualenvwrapper.

Remove venv in makefile

---

notifications_utils/recipients.py

Since `Columns` now implements `__contains__` we don’t have to fuss around so much to find out whether an instance contains a given key. This is more idiomatic, shorter and easier to read.

Refactor membership checking of `Columns` instances

---

notifications_utils/clients/statsd/statsd_client.py
tests/test_statsd_client.py

we send lots of statsd messages. If there's a problem with statsd, it's likely to be a high volume at once, which means we're likely to trip the pagerduty P1 error threshold
we see lots of statsd errors when cells roll. This is probably because there's just another moving cog - the internal DNS server, hosted on each cell. cells roll often and without our knowledge
there's nothing we can do about these errors, and they resolve themselves within seconds
there's a risk we may not see these messages at all if they're reduced to warning level, however, we can look at a tool like sentry if this is something we're concerned about
If the DNS lookup fails (and it's not cached) we'll raise an exception, skip sending the statsd data, and then carry on with regular program flow - which may well try …

statsd error cleanup - reduce logging and cache dns failures

---

notifications_utils/formatters.py
tests/test_formatters.py

This pull request allows users to include tilde and backtick characters in their emails without them sometimes disappearing. 
Tilde and backticks are used to define strikethrough and code snippets respectively.
Strikethrough in Markdown is specified using double tildes, for example:
```
This is ~~not~~ some `code`
```
Becomes
> This is ~~not~~ some `code`
We don’t support either of these formatting options and we remove them by just outputting the text, for example:
> This is not some code
This is bad if you’re using tildes or backticks for other purposes, for example as ‘special’ characters in a password.
This commit fixes the problem by removing strikethrough and code snippets from the Markdown rules that get applied. This is better than our previous approach of overriding the rules we …

Remove more markdown formatting rules to prevent characters disappearing 

---

notifications_utils/formatters.py
tests/test_formatters.py

We use a library called Bleach for escaping dangerous HTML in our template content. It doesn’t seem to handle things which look like HTML entities (for example `&copy;` or `&gt;`) but contain unexpected characters (the only one I’ve found so far is a question mark, for example `&?a;`).
This results in the last character of an escape sequence being replaced with a semicolon. I haven’t dug into the Bleach source deeply enough to identify where the problem is, and which other characters might affect it.
But a fix is to use Python’s builtins to convert any escape sequences to their unicode equivalent, and then escape them again. This seems to not get confused the way Bleach does.
We can then pass the output of this to Bleach, which passes through stuff that’s already properly encoded.
This …

Fix bug with double semicolons appearing in sequences of special characters 

---

notifications_utils/field.py
requirements_for_test.txt
setup.cfg
tests/test_recipient_csv.py

Flake8 Bugbear checks for some extra things that aren’t code style errors, but are likely to introduce bugs or unexpected behaviour. A good example is having mutable default function arguments, which get shared between every call to the function and therefore mutating a value in one place can unexpectedly cause it to change in another.
This commit enables all the extra warnings provided by Flake8 Bugbear.
Matches the work done in other repos:
- https://github.com/alphagov/notifications-admin/pull/3172
- https://github.com/alphagov/notifications-api/pull/3071

Do extra code style checks with flake8-bugbear

---

setup.cfg

As discussed in [1]. This has no effect on the existing imports.
[1]: https://github.com/alphagov/notifications-api/pull/3175#issuecomment-795530323

Update isort config to match that in API

---

notifications_utils/field.py
notifications_utils/formatters.py
notifications_utils/template.py
tests/conftest.py
tests/test_formatters.py
tests/test_template_types.py

'jinja2.Markup' is deprecated and will be removed in Jinja 3.1. Import 'markupsafe.Markup' instead.
PytestDeprecationWarning: @pytest.yield_fixture is deprecated. Use @pytest.fixture instead; they are the same.

Clean up some deprecated things

---

tests/test_field.py

We recently had an incident where changes in the code broke optional placeholders with linebreaks in them.
We should protect against that in the future by having unit tests checking for those cases.

Test detection and formatting of conditional placeholder with line-break in it

---

tests/test_serialised_model.py
tests/test_template_types.py

As of https://github.com/python/cpython/commit/4a12a178f4a6b9a59d97fecc727f2b6b28dfc85f the exception message for instantiating a class with abstract methods is only pluralised if there is more than one abstract method.
Our tests were expecting the exception message to always be pluralised.
This means the tests fail on Python versions greater than 3.9.0. This commit makes the tests pass with both (incorrectly) pluralised and non-pluralised versions of the message.

Reflect correctly pluralised exception message

---

requirements_for_test.txt

We need to keep the Celery version at the lowest version of used among any of our apps. Antivirus is on v4.4. We need to upgrade the apps before we can upgrade the common version in this repo, and we shouldn’t block other PRs to this repo in the meantime.

Don’t try to upgrade Celery to a newer version

---

notifications_utils/international_billing_rates.yml

See email chain "International SMS rules" for more details.
I've also added a header to clarify that the original "attributes"
shouldn't be modified, as discussed with the team.

Fix docs for international SMS to Lesotho

---

notifications_utils/international_billing_rates.yml

This file contains many additional fields, beyond the billing rates.
After comparing with related spreadsheets and asking the team, this
documents what all the fields and their values mean, as this isn't
obvious or readily available elsewhere.

Add schema for fields in int. billing rates YAML

---

CHANGELOG.md
notifications_utils/recipients.py
notifications_utils/version.py
tests/test_recipient_csv.py
tests/test_recipient_validation.py

This matches what we call the feature in the UI and documentation, after we changed the name in https://github.com/alphagov/notifications-admin/pull/3479

Rename `RecipientCSV.whitelist` to `RecipientCSV.guestlist`

---

notifications_utils/recipients.py
notifications_utils/version.py
tests/test_recipient_csv.py

Skip processing rows past 100,000 sooner 
In 26443fa I added an efficiency improvement which avoids trying to process the contents of spreadsheet rows once we’ve iterated past the maximum number of rows we allow.
This is good, because it means we don’t waste time trying to validate a million phone numbers, for example.
However it could be even better because we’re still doing some processing of these rows to put them into a data structure, which we then throw away.
So this commit adds the row count check earlier, which means it’s as fast to process a million rows as it is to process 100,000 rows.
***
Row count | Before | After
---|---|---
100,001 | 8.37s | 8.34s
1,000,000 | 12.14s | 8.96s

Skip rows past 100,000 sooner

---

CHANGELOG.md
notifications_utils/formatters.py
notifications_utils/recipients.py
notifications_utils/version.py
tests/test_recipient_csv.py

Doing `str.replace` is relatively expensive, and it has no effect when performed on an empty string. So we can make this function a bit more efficient by short circuiting when given an empty input.
`37.0s`
`15.8s`
If a spreadsheet has many empty columns we dutifully store those empty values against an empty column header, only to never look at them again. This takes extra time because the process of storing them is a bit more involved that just a `dict.update`.
By skipping storing these values we can make processing a spreadsheet a bit more efficient.
`15.8s`
`5.3s`
7&times; faster

Make processing empty cells faster

---

Makefile
notifications_utils/version.py
scripts/bump_version.py

Previous version | Command | New version | Correct
---|---|---|---
50.0.1 | `make version-patch` | 50.0.2 | ✅
50.0.1 | `make version-minor` | 50.1.1 | ❌
50.1.1 | `make version-major` | 51.1.1 | ❌
Previous version | Command | New version | Correct
---|---|---|---
50.0.1 | `make version-patch` | 50.0.2 | ✅
50.0.1 | `make version-minor` | 50.1.0 | ✅
50.1.1 | `make version-major` | 51.0.0 | ✅

Fix calculation of minor and patch version numbers

---

CHANGELOG.md
notifications_utils/recipients.py
notifications_utils/version.py
tests/test_recipient_csv.py

https://www.pivotaltracker.com/story/show/177535141
This PR does two things:
- Introduces timeout functionality to avoid RecipientCSV
getting stuck processing massive CSVs.
- Rewrites / removes some the tests for this class, partly
to avoid the timeout but also just make it faster!
Please review commit by commit.
```
time pytest
pytest  49.66s user 2.62s system 97% cpu 53.573 total
time pytest
pytest  28.59s user 2.46s system 96% cpu 32.184 total
```
These are for [previewing an uploaded CSV in the Admin app](https://github.com/alphagov/notifications-admin/blob/925f86aa705583e920ea4f0300c3f85fd8546c90/app/main/views/send.py#L645).
Note: these might be a bit dodgy because there's no way to filter for the "/check/" URLs in Kibana: you can't search / filter for non-alphanumeric characters in …

Speed up tests and code for RecipientCSV

---

CHANGELOG.md
notifications_utils/recipients.py
notifications_utils/version.py
tests/test_recipient_csv.py

https://www.pivotaltracker.com/story/show/177535141
This reverts commit 4fdf28412c4a74824f06607a19e9893b9e730326.
It turns out showing a contextual message for this error is hard,
as we would need to either:
- Show the error on an existing preview page, but be very careful
to structure the code so that none of the other checks run, since
these would trigger more timeout errors.
- Introduce a new error page. This is unprecedented for previewing
a CSV, where we always try to show a preview - this isn't possible
if the CSV is taking too long to process.
Taking a step back, we shouldn't really be adding timeout wrappers
around our code. A more future-proof approach would be:
- To monitor timings for all requests to our apps.
- Take action to improve performance where necessary.
While it's …

Revert "Timeout processing RecipientCSV rows"

---

CHANGELOG.md
notifications_utils/celery.py
notifications_utils/version.py
tests/test_celery.py

https://www.pivotaltracker.com/story/show/180693991
This should help debug the failures we're seeing for one of the
nightly tasks - create-nightly-notification-status-for-day - even
though the task gets to the point of logging a success.
It's worth noting Celery is probably emitting useful logs, but we
supress them [1]. It looks like we used to log an exception [2], 
but somehow this changed to 'error' in [3].
Logging an exception means we automatically get a stacktrace [4].
The call to "super()" is unnecessary:
- We don't do it for "on_success".
- It wasn't tested.
- The overridden method does nothing [5].
- None of the docs say to call "super()".
[1]: https://github.com/alphagov/notifications-api/blob/master/scripts/paas_app_wrapper.sh#L9
[2]: …

Log stacktrace when a task fails

---

CHANGELOG.md
notifications_utils/version.py
setup.py

While the package can always fetch new holidays via the GOV.UK API,
the latest version of the packages also caches ones for next year,
which means we can avoid unnecessary web requests.

Bump govuk-bank-holidays to latest version

---

CHANGELOG.md
notifications_utils/clients/redis/redis_client.py
notifications_utils/version.py
scripts/bump_version.py
setup.py
tests/test_redis_client.py

We don't use them, we haven't for a while since we simplified our redis usage.
* Deprecate the following unused `redis_client` functions:
- `redis_client.increment_hash_value`
- `redis_client.decrement_hash_value`
- `redis_client.get_all_from_hash`
- `redis_client.set_hash_and_expire`
- `redis_client.expire`

Purge unused redis functions

---

CHANGELOG.md
notifications_utils/clients/redis/redis_client.py
notifications_utils/version.py
tests/test_redis_client.py

https://www.pivotaltracker.com/story/show/180663519
This renames the "delete_cache_keys_by_pattern" function
and makes it behave the same as all the other functions:
exceptions are caught and logged by default.
There are pros and cons to ignoring Redis errors:
- Users get a better experience (fallback to the DB).
- Redis may end up with stale data (due to updates).
At the moment we're not sure which is better, but we can
at least be consistent. The new "raise_exception" parameter
also means we can override the default behaviour.
Please review commit by commit, as there are quite a few
refactoring steps to support the change.

Standardise behaviour of Redis "delete" functions

---

requirements_for_test.txt

No reason for it to be pinned, nothing interesting in the git
history. Brings it up to parralel with our other apps.
Also remove the pyup ignore as again no reason for this to be
ignored.

Bump celery requirement to version 5

---

CHANGELOG.md
notifications_utils/version.py
setup.py

https://www.pivotaltracker.com/story/show/181498273
This fixes:
OSError: Could not find lib geos_c or load any of its variants ['/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib', '/usr/local/lib/libgeos_c.dylib'].
Relevant line in CHANGES.txt [^1]:
- Add /opt/homebrew/lib to the list of directories to be searched for the GEOS shared library.
Other changes are (apparently) just bug fixes and new features. I
didn't see any deprecation warnings when running the tests.
[^1]: https://github.com/shapely/shapely/blob/main/CHANGES.txt

Bump shapely to 1.8.0 to support geos on Mac M1

---

CHANGELOG.md

https://www.pivotaltracker.com/story/show/181498273
I had to check these older changes before upgrading from 44.2.0 in
download-api, so I may as well document them.

Backfill changelog down to 44.2.1

---

notifications_utils/version.py
requirements_for_test.txt
setup.py

There's nothing in the latest version (3.3.0) that looks dangerous, so
by loosening the requirements here we can keep pyproj up to date in
notifications-admin.

Unpin pyproj

---

CHANGELOG.md
notifications_utils/version.py
setup.py

https://www.pivotaltracker.com/story/show/181588331
We decided we prefer to use unpinned dependencies in this repo [^1]
so this makes all of them consistent.
I've also removed two dependencies which were added in response to
PyUp generating to many update PRs [^2]. Since we now have a strategy
I think we should put them back and solve the issue more explicitly
in the apps that need them.
[^1]: https://docs.google.com/document/d/1DO6nFV9E7Qr94_NnUfYsMKFrKTvcjn0ESjjDHodfQUk/edit#heading=h.pohfahyz07ro
[^2]: https://github.com/alphagov/notifications-utils/commit/d0fa02026d525ea537785b91255db182b01e6caf

Unpin most dependencies and remove redundant ones

---

CHANGELOG.md
notifications_utils/version.py
setup.py

https://www.pivotaltracker.com/story/show/181588331
Requiring a higher version leads to an error e.g. in API
There are incompatible versions in the resolved dependencies:
botocore<1.25.0,>=1.24.38 (from boto3==1.21.38->notifications-utils@ git+https://github.com/alphagov/notifications-utils.git@55.1.3->-r requirements.in (line 34))
botocore==1.22.4 (from awscli==1.21.4->awscli-cwlogs==1.4.6->-r requirements.in (line 32))
There are no newer versions of awscli-cwlogs so for now we need to
accommodate the lower version of botocore it requires, which we can
with version 1.19.4 of boto3 [^1].
[^1]: https://github.com/boto/boto3/commit/a8ea399aff0adea0b09f0d2fda8a0b679fcc01f0#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52R6

Lower minimum version of boto3 dependency

---

notifications_utils/insensitive_dict.py
notifications_utils/recipients.py
notifications_utils/version.py
tests/test_insensitive_dict.py

Dicts became insertion-ordered in Python 3.6. This behaviour was considered ‘guaranteed’ in Python 3.7<sup>1</sup>. At the moment we use Python 3.9 in production.
This means we no-longer need `OrderedDict` as an extra import.
---
1. https://mail.python.org/pipermail/python-dev/2017-December/151283.html

Remove use of OrderedDict

---

CHANGELOG.md
notifications_utils/formatters.py
notifications_utils/markdown.py
notifications_utils/template.py
notifications_utils/version.py
tests/test_formatters.py
tests/test_template_types.py

So that we can reuse this in other places (specifically gov.uk/alerts) it needs to be a more bit flexible.
In short, this pull request makes it so that:
- `autolink_sms` is renamed to `autolink_urls`
- consumers of the `autolink_urls` function can specify which classes get applied to the `<a>` element, so that the link can be styled with CSS
- the `autolink_urls` function also picks up URLs which don’t start with `http://` or `https://`, to match what mobile phones do when showing text messages or emergency alerts

Make URL autolinking more flexible

---

notifications_utils/formatters.py
notifications_utils/version.py
tests/test_formatters.py

Email addresses have two things which could be interpreted as URLs which should be made in to links:
1. the domain name itself, eg @example.com
2. the local part when it contains a dot, eg firstname.lastname
Either the whole email address should be linked or none of it should be linked. This commit preserves the previous behaviour where no part of the email address was linked.
It does this by modifying the regular expression using word boundaries (`\b`) and negative lookahead/lookbehinds to sniff out when something that might be a link starts or ends with an `@`, suggesting it is part of an email address.
Before | After
---|---

Fix auto linking domains in email addresses

---

notifications_utils/formatters.py
notifications_utils/version.py
tests/test_formatters.py

We fixed the domain name being linked in email addresses when the address was in the format `test@example.com`.
However when the address was in the format `test@test.example.com` `example.com` was still being made into a link because the `.` between `test` and `example` is seen as a word boundary.
This commit fixes that by adding `.` to the negative lookbehind. This means anything which looks like a URL but starts with `.` or `@` will not be made into a link.

Fix parts of email addresses wrongly being linked

---

notifications_utils/jinja_templates/letter_image_template.jinja2
notifications_utils/version.py
tests/test_template_types.py

This changes the letter_image_template.jinja template to use the `.govuk-visually-hidden` class instead of the `.visually-hidden` class. There is no difference in appearance, but we removed the styles for the `.visually-hidden` class in https://github.com/alphagov/notifications-admin/pull/4326 so can no longer use it.

Change .visually-hidden class to .govuk-visually-hidden in letter image template

---

notifications_utils/formatters.py
notifications_utils/sanitise_text.py
notifications_utils/version.py
tests/test_formatters.py
tests/test_sanitise_text.py

This is a new whitespace character we didn’t know about. It appears to perform the same function as a non-breaking space (i.e. preventing a line break between words when used instead of a normal space).
If we don’t specifically account for it then it gets treated like any other unusual unicode character. This means when a user tries copies some text into their template which uses this character they see this error:
> 'You cannot use  in text messages. It will not show up properly on everyone's phones.'
…which is unhelpful because it’s not obvious that the space between ‘use’ and ‘in’ is what’s being referred to.
Only a change in `sanitise_text.py` is required to fix this, but it seems reasonable to change it in `formatters.py` too where we use a different method to normalise the same set …

Treat narrow no break space like non breaking space when normalising and sanitising 

---

notifications_utils/field.py
notifications_utils/version.py
tests/test_field.py
tests/test_template_types.py

Presently the use of ampersands "&" in placeholders does not work as expected. This is because Jinja converts it to its special entity "&amp;". 
I have made adjustments to the Placeholder class so that this is done before hand.

Ampersand placeholder fix

---

CHANGELOG.md
notifications_utils/jinja_templates/email_template.jinja2
notifications_utils/template.py
notifications_utils/version.py
tests/test_template_types.py

this is a breaking change, but is just a variable rename. It felt good to do just to avoid any confusion with what each field is for though.

make HTMLEmailTemplate take brand_alt_text instead of brand_name

---

Makefile

Branch was called `master`, is now called `main`
We look at this branch to see what the current version is before incrementing it.

Reflect renaming to `main` in version script

---

CHANGELOG.md
notifications_utils/clients/zendesk/zendesk_client.py
notifications_utils/version.py
tests/clients/zendesk/test_zendesk_client.py

Zendesk supports creating tickets with HTML:
https://developer.zendesk.com/api-reference/ticketing/tickets/tickets/#create-ticket
We'd like to generate a report about email brandings and it would be nice to include links to them (but with the brand name as the clickable text).

Add support for HTML support tickets

---

CHANGELOG.md
notifications_utils/template.py
notifications_utils/version.py

We added the `encoding` argument to `Template` when we started counting the length of template content:
https://github.com/alphagov/notifications-utils/blob/a9b09d841b0abf928c145225c279b0cc7ae217df/notifications_utils/template.py#L8-L13
We needed to do this because determined the length by encoding the template to bytes then counting how many bytes there were. This meant we needed to know what encoding the text was in otherwise we might miscount. So we referred to `self.encoding` here:
https://github.com/alphagov/notifications-utils/blob/1ab5a4428189dac8e3944bb74e7eeb8b83d9a52f/notifications_utils/template.py#L167-L174
Practically we always deal with text in UTF8, so this property was hard coded on the class in
https://github.com/alphagov/notifications-utils/blob/9653f28e0448c8a20b97a4097f …

Remove `Template.encoding`

---

notifications_utils/celery.py
notifications_utils/clients/antivirus/antivirus_client.py
notifications_utils/clients/redis/__init__.py
notifications_utils/clients/redis/redis_client.py
notifications_utils/clients/redis/request_cache.py
notifications_utils/clients/statsd/statsd_client.py
notifications_utils/field.py
notifications_utils/formatters.py
notifications_utils/international_billing_rates.py
notifications_utils/logging.py
notifications_utils/markdown.py
notifications_utils/pdf.py
notifications_utils/postal_address.py
notifications_utils/recipients.py
notifications_utils/request_helper.py
notifications_utils/s3.py
notifications_utils/sanitise_text.py
notifications_utils/statsd_decorators.py
notifications_utils/template.py
notifications_utils/version.py
tests/clients/test_redis.py
tests/test_markdown.py
tests/test_recipient_csv.py
tests/test_recipient_validation.py
tests/test_take.py
tests/test_template_types.py

f-strings were added in Python 3.6. Some of our older code predates Python 3.6 and therefore couldn’t use f-strings where it was written.
This pull request replaces uses of `str.format()` to use f-strings, which are generally easier to read and result in fewer lines of code.
The only ones I’ve left are where `str.format` was being passed several complex expressions, which are easier to read line by line as separate arguments.

Prefer f-string formatting

---

notifications_utils/international_billing_rates.py
notifications_utils/version.py

As a relative path it doesn’t work when utils is installed as a dependency in other apps – the file can’t be found
Example of the error in the API app:
```
E   FileNotFoundError: [Errno 2] No such file or directory: 'notifications_utils/international_billing_rates.yml'
```

Make path to international rates file absolute

---

Makefile

As per https://github.com/alphagov/notifications-api/pull/3659
Before:
After:

Run tests on recommended number of CPU cores

---

CHANGELOG.md
notifications_utils/clients/redis/__init__.py
notifications_utils/version.py
tests/clients/test_redis.py

We want to move from having a single message limit per day to having daily limits based on the notification type. Let's support both for now so we can roll out backwards-compatible changes.

Support notification type in rate limit cache key

---

setup.py

We started to get a lot of test failures in utils after the release of pyproj 3.4.1. We pulled in the latest release automatically for tests directly on the utils repo.
Let's pin to below that version for now, so that tests can pass. We should investigate further:
1) What's changed
2) Whether the 'issue' will be fixed in pyproj or if we should look at updating our use of the lib to become compatible with what's changed.

Pin pyproj below 3.4.1

---

CHANGELOG.md
notifications_utils/polygons.py
notifications_utils/version.py
setup.py
tests/test_polygons.py

Version 3.4.1 of pyproj changed the ESPG codes to be upper case, which means that our tests now fail (https://github.com/pyproj4/pyproj/pull/1162).
This change updates our code to also use upper case codes, and bumps the minimum version of pyproj to ensure that we're always using a version which also uses the upper case codes.

Update code for version 3.4.1 onwards of pyproj dependency

---

CHANGELOG.md
notifications_utils/bank_holidays.py
notifications_utils/data/bank-holidays.json
notifications_utils/letter_timings.py
notifications_utils/version.py
setup.py
tests/test_bank_holidays.py

govuk_bank_holidays is a package maintained by the Ministry of Justice which provides functionality to detect working/non-working days, including weekends and bank holidays. They have cached bank holidays data as part of their package. This means that any apps pulling in notifications_utils and checking bank holidays data need to manually keep the indirect dependency govuk_bank_holidays up-to-date, which we don't have a good process for.
Let's instead cache the bank holidays ourselves and use our own data. We can add a test to notifications_utils to check that bank holiday data is up-to-date, which gives us greater assurance that our non-working-day checks will remain valid into the future.

Use locally-cached bank holidays data

---

CHANGELOG.md
notifications_utils/clients/zendesk/zendesk_client.py
notifications_utils/version.py
tests/clients/zendesk/test_zendesk_client.py

Bump to version 61.1.0
---
This should get us a step closer to automatically sending DWP their weekly report.
1) In `notifications-api`, `pip install -e ../notifications-utils`
2) `pip install flask-shell-ipython`
3) `flask shell`
4) ```python
import datetime
from io import StringIO
from app import zendesk_client
from notifications_utils.clients.zendesk.zendesk_client import *
csvfile = StringIO('a,b,c\n1,2,3')
comment = NotifySupportTicketComment(
body='this is an automatic comment',
attachments=[
NotifySupportTicketAttachment(filename='blah.csv', filedata=csvfile, content_type='text/csv'),
],
public=False
)
zendesk_client.update_ticket(
ticket_id=5177772,
comment=comment,
status=NotifySupportTicketStatus.PENDING,
due_at=datetime.datetime(2023, 2, 1, 12, 0, 0)
)
```

Add zendesk client methods for updating tickets

---

CHANGELOG.md
notifications_utils/postal_address.py
notifications_utils/version.py
tests/test_postal_address.py

This will let us annotate addresses as BFPO addresses and help our print provider process the letters more efficiently. In theory this change is optional - we could send these across as standard unstructuredAddresses, but it will require more manual work by our print provider/royal mail so it would be nice to not do that.
This shouldn't reject any addresses that were previously accepted, but it will change the normalised form of BFPO addresses.
Ideally we'll update admin, api and template-preview all in fairly quick succession (and the same day) but in _theory_ I think this should be safe to go out separately. The address might be normalised differently in different places (eg DB vs letter address block) but nothing should _break_. I think I've tested various combinations fairly …

Handle and normalise BFPO addresses

---

notifications_utils/postal_address.py
notifications_utils/version.py
tests/test_postal_address.py

Although we consider this an invalid address, we should still include the country in the output as it was provided coming in.
Some apps, eg admin, process the address multiple times and so if we drop off the country, the latter processing steps won't consider the address invalid. We may want to fix that separately, but let's be safe on this side.

Include country for normalised BFPO

---

notifications_utils/jinja_templates/letter_image_template.jinja2
notifications_utils/version.py

[This pull request on admin](https://github.com/alphagov/notifications-admin/pull/4648) introduced a visual bug due to its use of `nth-of-type` assuming `.letter:nth-of-type(even)` would affect even-numbered elements matching this selector: `div.letter`.
It actually matches even-numbered `div` elements, filtered by whether they have the `letter` class or not.
You will be able to match even-numbered pages in CSS in future (see https://css-tricks.com/css-nth-of-class-selector/) but until then, we can use Jinja to add ~~a specific class~~ classes to indicate if a page is odd or even this instead.
Uses BEM syntax to indicate a state of page. There is currently no CSS in admin targeting this class so this can be merged with no impact.
Edit: I've updated this so it adds either `page--odd` or …

Add odd/even class to all letter pages

---

CHANGELOG.md
notifications_utils/jinja_templates/letter_pdf/_main_css.jinja2
notifications_utils/version.py

The fonts we use in letters support all character sets we have tested, except for Chinese.
This commit adds WenQuanYi Zen Hei<sup>1</sup> to our font stack. This is a font which:
- is open source and [can be installed in our Docker images](https://github.com/alphagov/notifications-template-preview/pull/725)
- has glyphs for Chinese character sets
The way CSS works is that if the first font in the stack doesn’t have glyphs for a particular character it will fall back to the next font, then the next font, etc.
***
1. https://en.wikipedia.org/wiki/WenQuanYi

Add support for Chinese character sets in letters

---

CHANGELOG.md
notifications_utils/logging.py
notifications_utils/version.py

This will eat through our logging allowance and we definitely don't treat them as exceptions.

Stop logging formatting issues as errors/exceptions

---

CHANGELOG.md
notifications_utils/clients/zendesk/zendesk_client.py
notifications_utils/version.py
tests/clients/zendesk/test_zendesk_client.py

At the moment all support tickets are raised with a notify ticket type assigned immediately (generally, non-technical). This is often misleading as we get technical queries through this channel as well. We can have a clearer triage process if tickets come in with no type, and then the first person to look at the ticket can assign it to either non-technical (product/design/research/general support) or technical (requiring dev input).

Allow zendesk ticket creation without notify type

---

CHANGELOG.md
notifications_utils/template.py
notifications_utils/version.py
tests/test_template_types.py

This means that it can be overidden by subclasses.
Previously if a subclass tried to implement a `page_count` property then it would cause an exception where the `__init__` method is trying to assign to `self.page_count`.
Letting subclasses define their own `page_count` will mean there’s a nice place to put logic about how many pages are in a templated letter with an attachment, and on what page the attachment starts.
***
For convenience we can then add the following useful attributes and properties to all letter template classes:
- `max_page_count`
- `max_sheet_count`
- `too_many_pages` (requires subclasses to implement `page_count`)

Add some useful properties to letter template classes

---

CHANGELOG.md
notifications_utils/clients/zendesk/zendesk_client.py
notifications_utils/version.py
requirements_for_test.txt
tests/clients/zendesk/test_zendesk_client.py

We're seeing increasing numbers of errors in our logs because the Zendesk client has returned a 422 status code. This happens when a user has been suspended due to submitting spam tickets.
When this happens, we now log a warning and not an error.

Downgrade errors when a suspended user tries to create a Zendesk ticket

---

CHANGELOG.md
notifications_utils/template.py
notifications_utils/version.py
tests/test_template_types.py

Removes the `postage` argument from `LetterImageTemplate` in favour of getting `postage` from the template `dict` (can still be overridden by setting `template_instance.postage`). This will be nicer than how we currently override postage on a template: https://github.com/alphagov/notifications-admin/blob/867bd24d81e8003c2ca4b44d8c71ed497d86d1d4/app/main/views/uploads.py#L269-L272
The `page_count` argument of `LetterImageTemplate` is now optional until the template is rendered (calling `str(template)`). This means we can avoid dummy values like we’re using here: https://github.com/alphagov/notifications-admin/blob/867bd24d81e8003c2ca4b44d8c71ed497d86d1d4/app/utils/templates.py#L25

Tweak how `LetterImageTemplate` is called with `page_count` and `postage`

---

CHANGELOG.md
notifications_utils/clients/redis/request_cache.py
notifications_utils/version.py
tests/clients/redis/test_request_cache.py

According to the Redis metrics from the PaaS the most we’ve used in the last 30 days is about 20% of the 568mb provided by our plan.
The longer we keep things in the cache, the more likely they are to be served from it, rather than having to go to the origin  (the API). Serving things from the cache is generally faster than serving them from the origin.
The worst case scenario is that by quadrupling the expiry time we quadruple the number of items in the cache. This would still only use 80% of the available memory, which still gives some headroom.
The worst case scenario is unlikely, because many of the things we cache at the moment will be accessed frequently. This means that they will get re-accessed and re-cached soon after they expire.
Most of the performance benefit here will come …

Extend default request cache expiry from 7 to 28 days

---

CHANGELOG.md
notifications_utils/jinja_templates/letter_image_template.jinja2
notifications_utils/template.py
notifications_utils/version.py
tests/test_template_types.py

So that we can jump directly to it using an anchor link.
Separate element instead of adding an `id` to the image so that we can control the exact positioning without changing the position of the visible element (i.e. the preview of the page itself).
Also adds `loading=eager` to the first page of the attachment as a hint to browsers. If the user is jumped straight to the first page of the attachment then we should try to load that as quickly as possible, rather than loading all the intermediary templated pages first.

Invisibly mark the first page of a letter attachment

---

.pre-commit-config.yaml
CHANGELOG.md
notifications_utils/celery.py
notifications_utils/clients/antivirus/antivirus_client.py
notifications_utils/clients/redis/redis_client.py
notifications_utils/clients/statsd/statsd_client.py
notifications_utils/clients/zendesk/zendesk_client.py
notifications_utils/logging.py
notifications_utils/recipients.py
notifications_utils/s3.py
notifications_utils/statsd_decorators.py
notifications_utils/version.py
pyproject.toml
requirements_for_test.txt
tests/clients/redis/test_redis_client.py
tests/clients/statsd/test_statsd_client.py
tests/clients/zendesk/test_zendesk_client.py
tests/test_base64_uuid.py
tests/test_celery.py
tests/test_logging.py
tests/test_statsd_decorators.py
tests/test_timezones.py

Removes the custom functionality to automatically try to inject variables into the log string. A whole host of our log messages were erroring out on this functionality because the variable didn't exist, or because we were logging out dictionaries which "".format() was trying, and failing, to handle.
Now that we've integrated Sentry, let's standardise on the "old-style" logging format, which looks something like this:
logger.info("Response %s took %.4f to generate", response.body, duration)
Python's logging system will automatically interpolate the message with the provided arguments, and sentry will group any error-level log messages as a single issue (the way we used to do things - like `logger.error(f"something went wrong: {exc}") would generate a unique sentry issue if exc generated a …

Remove auto-log formatting and standardise format

---

CHANGELOG.md
notifications_utils/countries/_data/synonyms.json
notifications_utils/version.py
tests/test_countries.py

If we want to display the correct names for countries we need to be able to map from the source data to what we consider the canonical names.
This commit adds data to our countries list so that we can do that.
Whether or not this is used for international SMS, it’s always good to make these mappings more robust and comprehensive for international letters.

Add mappings for international phone countries

---

notifications_utils/international_billing_rates.yml
notifications_utils/version.py
tests/test_international_billing_rates.py
tests/test_recipient_validation.py

note: some countries were not specified in the source spreadsheet so were defaulted to four billable units
code used to generate this was:
```
new_rates = {"1": 1, "20": 3, ......}
billing_yml_path = Path(__file__) / "international_billing_rates.yml"
with open(billing_yml_path) as yml_file:
data = yaml.safe_load(yml_file)
for country_code, metadata in data.items():
if country_code not in new_rates:
metadata["notes"] = "# not specified in MMG multiplier sheet so set to default of 4"
metadata["billable_units"] = new_rates.get(country_code, 4)
with open(billing_yml_path, "w") as yml_file:
yml_file.write(yaml.dump(data, default_flow_style=False, sort_keys=False))
```
then afterwards, i manually went through the international_billing_rates file to convert the little "notes" into a normal yaml …

update international sms multipliers

---

CHANGELOG.md
notifications_utils/pdf.py
notifications_utils/version.py
setup.py
tests/test_pdf.py

Addresses a vulnerability in PyPDF2
(https://github.com/alphagov/document-download-api/security/dependabot/16).
Also, PyPDF2 is now deprecated and development is continuing back on `pypdf`:
* https://pypi.org/project/PyPDF2/
* https://pypi.org/project/pypdf/
---
Although we are going up a major version, the breaking changes are minimal and none of them appear to affect us:
https://pypdf2.readthedocs.io/en/latest/meta/CHANGELOG.html
https://pypdf.readthedocs.io/en/latest/meta/CHANGELOG.html#version-3-1-0-2022-12-23

Switch from PyPDF2->pypdf>=3.9.0

---

CHANGELOG.md
notifications_utils/field.py
notifications_utils/markdown.py
notifications_utils/version.py
tests/test_field.py
tests/test_field_html_handling.py
tests/test_template_types.py

There is still some wonky stuff after this patch (eg <strong> tags in weird places around link personalisation in letters, and link hrefs with personalisation spans in them is funky), but the situation is better.
---
With the following markdown:
```markdown
[link](text)
[link](prefix ((personalised)))
[link](((personalised)) suffix)
[link](prefix ((personalised)) suffix)
```
```html
<p style="Margin: 0 0 20px 0; font-size: 19px; line-height: 25px; color: #0B0C0C;"><a
style="word-wrap: break-word; color: #1D70B8;" href="text">link</a><br/><a
style="word-wrap: break-word; color: #1D70B8;" href="prefix <span class='placeholder'>((personalised">link</a>)&lt;/span&gt;)<br/><a
style="word-wrap: break-word; color: #1D70B8;" href="<span class='placeholder'>((personalised">link</a>)&lt;/span&gt; …
```

HTML encode personalisation parentheses so they don't break links

---

CHANGELOG.md
notifications_utils/jinja_templates/letter_pdf/_main_css.jinja2
notifications_utils/markdown.py
notifications_utils/version.py
tests/test_template_types.py

When a QR code contains a placeholder we render a ‘placeholder’ box instead, which has a dashed border.
If the text of the placeholder or its prefix/suffix is long, then this causes the text to wrap inside the placeholder box. Because the placeholder box is a relatively narrow fixed width this:
- happens easily
- does not look very good
- makes the text harder to read
This commit adds some extra HTML elements which allow us to style the box and its contents separately.
This way the contents can overflow the box without looking messy. The width of the text is therefore limited to the width of the column, as it is for other URLs and placeholders.
***
By colour-coding the elements you can see how this is constructed:
***
Ideally this would use `vertical-align: middle` to centre the text, …

Style the QR code placeholder so it looks better when the placeholder text is long

---

CHANGELOG.md
notifications_utils/markdown.py
notifications_utils/version.py
tests/test_template_types.py

Our current syntax for QR codes is pretty gnarly, especially when it comes to using placeholders as all or part of the URL, for example
```
[qr](https://www.example.com?reference=((placeholder)))
```
If I saw triple closing brackets like that in some code I was writing I would consider if there was a better way to factor the code to make it easier to read. And this example isn’t full-blown code, it’s our templating.
We initially went with this syntax because it’s consistent with how Markdown links work. However it also differs from Markdown links in that the label part (the `[qr]`) is fixed and can’t be changed. So the reusable knowledge is more hypothesis than fact.
Markdown links do have the advantage of being inline, in other words they can be inserted in the middle of a paragraph. But …

Use a simpler syntax for QR codes in letters

---

CHANGELOG.md
notifications_utils/recipients.py
notifications_utils/template.py
notifications_utils/version.py
tests/test_recipient_csv.py
tests/test_template_types.py

The exception raised by the contains useful information about the problem at hand, such as the data passed into the QR code, and the actual & max length of QR codes.
Let's pass this back instead of lose the information by only returning True/False. Then we can potentially display the bad QR code data to the user if it's helpful.

Return QR code validation error from check

---

CHANGELOG.md
notifications_utils/markdown.py
notifications_utils/version.py
tests/test_markdown.py
tests/test_template_types.py

We automatically make URLs in letters bold by adding a `<strong>` tag around them. We also remove the protocol (for example `https://`) from the URL.
If we want to reconstruct the full URL later down the line, we need to store the original protocol somewhere.
HTML allows for arbitrary attributes to be created as long as they are prefixed with `data-`. So this PR introduces a new attribute on the `<strong>` tag which stores the original protocol for later use.
***
Adding the `<strong>` tag happens before we look for our QR code syntax.
This means that URLs going into QR codes end up with a small bit of markup in them. This prevents them from going to the original URL when scanned.
This PR:
- removes the `<strong>` tag
- restores the protocol
- preserving any placeholders
Ideally we …

Remove `<strong>` tags from links in QR codes

---

CHANGELOG.md
notifications_utils/markdown.py
notifications_utils/qr_code.py
notifications_utils/version.py
tests/test_markdown.py
tests/test_template_types.py

We’ve introduced a new, friendlier syntax for QR codes in letters, which looks like
```
QR: https://www.example.com/
```
The old one looks like:
```
[QR](https://www.example.com/)
```
We should remove the old one so there’s only one way to do things.
We should remove it now (before we launch the feature) so that we don’t have to worry about it being a breaking change for teams using the old syntax.
This also includes making the regex for the new syntax a bit more flexible so it can handle leading whitespace.

Remove the old syntax for QR codes in letters

---

CHANGELOG.md
notifications_utils/recipients.py
notifications_utils/version.py
tests/test_recipient_validation.py

As part of the work being done on [this](https://trello.com/c/IgLu00uK/449-add-error-summaries-to-profile-page-forms) error summaries ticket, the current InvalidPhoneError messages are being updated.
There are different validation scenarios ie uk numbers vs international numbers. The previous errors were quite generic while the new error messages are more specific and are tied to the validation parameters. For example the error message "not enough digits" is being replaced by either "Mobile phone number must be at least 8 digits long" for International numbers or "Mobile phone number must be at least 10 digits long" for UK numbers.
I have attached before and after screen shots of the various error messages. There may have to be a rethink of the new error message for invalid error messages …

Update InvalidPhoneError messages

---

notifications_utils/markdown.py
notifications_utils/version.py
tests/test_markdown.py

We removed the <strong> tags when rendering the QR code for preview/print, but because we override `_render_qr_data` for the validation renderer we had missed it there.
Let's move the <strong> stripping to before we pass the data into the renderer so it takes effect everywhere.

Make sure QR code <strong> tags are removed

---

CHANGELOG.md
notifications_utils/formatters.py
notifications_utils/sanitise_text.py
notifications_utils/version.py
tests/test_formatters.py
tests/test_sanitise_text.py

These are obscure unicode characters which are used to indicate that a new line should be treated as a line break or a new paragraph.
Because they are not in the GSM-7 character set we can’t send them without incurring double-charging. For this reason we validate them out at the time of template editing, and the user gets this unhelpful error message:
***
This PR adds these characters to the list of whitespace we remove and sanitise out.

Remove line and paragraph separators from text message content

---

CHANGELOG.md
notifications_utils/markdown.py
notifications_utils/version.py
tests/test_markdown.py

We have switched to using the syntax `QR: link/data` in letter template content for rendering QR codes. However, we use mistune to parse the letter content into HTML, and that just so happens to take our "old" QR code syntax of `[QR](link/data)` and turn it into `QR: link/data`, which then can get picked up as the new-style syntax.
I had a quick look to see if we could force the old-style syntax to only render as links, not QR codes, but the solution felt slightly convoluted (need to feed some indicator/argument between `link`/`autolink` and `paragraph` methods) and I don't think it's really worth doing. We can technically support both syntaxes, but only advertise the simpler one. Note also that the "old-style" `[QR]()` syntax only resolves to an actual QR code if it's the only thing in …

Fix QR code rendering with old [QR]() syntax

---

CHANGELOG.md
notifications_utils/markdown.py
notifications_utils/version.py
tests/test_markdown.py
tests/test_template_types.py

When we first added markdown-style formatting to emails – before letters were even a thing – we decided to translate links into a text-only-friendly representation, so `[link](url)` became `link: url`:
https://github.com/alphagov/notifications-utils/blob/13abc3f200603c46c35c76b0dc40718c7efe3ac2/notifications_utils/formatters.py#L149-L150
This is because we did not – officially or unofficially – support link text in emails.
When we added letter templates we shared the same method for rendering links, so letter templates also got this same plain-text representation of Markdown-style links.
The idea was that if you pasted a Markdown-style link into a template and didn’t realise it wasn’t supported the recipient wouldn’t get something which looked broken.
We later chose to make the URLs bold, …

Remove translation of markdown links in letters

---

CHANGELOG.md
notifications_utils/template.py
notifications_utils/version.py
tests/test_template_types.py

it's been unused since 2017[^1]
[^1]: https://github.com/alphagov/notifications-utils/pull/227

remove from_address from EmailPreviewTemplate

---

CHANGELOG.md
notifications_utils/jinja_templates/email_template.jinja2
notifications_utils/markdown.py
notifications_utils/version.py
tests/test_markdown.py
tests/test_template_types.py

Changes the doctype of our email template from XHTML1.0 strict to HTML5, to let us use the `hidden` attribute to hide our preheader.
https://trello.com/c/SeG6l0zU/375-change-email-doctype-to-html5
Note: the new template still has validation errors but they are due to our use of deprecated HTML4 features to stop email client programs stripping out our styles.
I tested [all the possible branding variants](https://github.com/alphagov/notifications-manuals/wiki/Email-template-documentation#possible-branding-variations-for-testing) of this template with [all the email clients we support](https://github.com/alphagov/notifications-manuals/wiki/Support-for-browsers,-email-clients-and-assistive-technologies#support-for-email-clients) and [all the asssitive technologies we …

Change emails to HTML5

---

notifications_utils/version.py

Somehow the script got this wrong previously and went from
https://github.com/alphagov/notifications-utils/blob/e7882987f0b0e4aa00d3aec9df3d53e9cae85440/notifications_utils/version.py#L8
to
https://github.com/alphagov/notifications-utils/blob/cfc571ca02e3f0a225859721a203e01302bbe4d2/notifications_utils/version.py#L8
This PR manually corrects that to increment the patch version by `1`, to `72.1.1`

Patch version bump to 72.1.1

---

scripts/bump_version.py

This makes the output of `make version-minor` and `make version-patch` consistent with the change to the README in 66248cede37e112344647f01aa3d684b62da617f which now says
https://github.com/alphagov/notifications-utils/blob/20ec6ceb960ae5b93a618ef87002459f390b46ff/README.md#L35

Always recommend updating CHANGELOG

---

CHANGELOG.md
notifications_utils/template.py
notifications_utils/version.py
tests/test_recipient_csv.py
tests/test_template_types.py

Moves this class and its related template file to the admin app, which is the only thing using it.
This allow us to inject overlay (UI) elements into the correct place, as we want to have an 'edit' button appear on the first page of English content. This may be any arbitrary depth into the letter.

Lift and shift LetterImageTemplate

---

notifications_utils/version.py
requirements_for_test.txt
setup.py

* don't package them by accident
* enforce the flask version so that they run

Fix unit tests

---

CHANGELOG.md
notifications_utils/jinja_templates/letter_pdf/print.jinja2
notifications_utils/template.py
notifications_utils/version.py
tests/test_template_types.py

This tag should only be present on the first page of a PDF we generate to send to DVLA.
In supporting bilingual letters, we generate two PDFs: a Welsh variant followed by an English variant.
We need to stop inserting the 'NOTIFY' tag on the English variant, and so need to be able to toggle the tag off, otherwise DVLA's printers get confused.

Allow hiding notify tag on letter print template

---

CHANGELOG.md
notifications_utils/version.py
setup.py

In an attempt to exclude the `tests` package, we excluded a lot of
notifications_utils.
```
In [1]: from setuptools import find_packages
In [2]: find_packages()
Out[2]:
['tests',
'notifications_utils',
'notifications_utils.clients',
'notifications_utils.testing',
'notifications_utils.countries',
'notifications_utils.clients.encryption',
'notifications_utils.clients.redis',
'notifications_utils.clients.antivirus',
'notifications_utils.clients.statsd',
'notifications_utils.clients.zendesk']
```
We should just exclude `tests`, rather than including the (top-level)
`notifications_utils`. The latter excludes all of the subpackages, which
then makes them inaccessible at their dot paths.
---
Was leading to errors like this when bumping utils on template-preview:
```
./scripts/run_with_docker.sh …
```

Fix utils packaging

---

CHANGELOG.md
notifications_utils/logging.py
notifications_utils/version.py
tests/test_logging.py

https://trello.com/c/pWDzU11r/567-fractional-timestamps-for-app-logs
Ideally we'd just include this in our `TIME_FORMAT`, but python's `strftime` has no ability to include even milliseconds. The python-default logging `datefmt` is augmented with milliseconds in the stdlib logging module via a hack, but this hack is disabled when a custom `datefmt` is supplied. So we have to add back our own hack to include precise time.
Use microsecond granularity as it should be enough to correctly order even log records that are generated immediately-consecutively in the same thread.

logging: add microseconds to time format via mixin class

---

CHANGELOG.md
notifications_utils/clients/redis/redis_client.py
notifications_utils/version.py
tests/clients/redis/test_redis_client.py

This adds a `decrby` method to the RedisClient so that we can change the cache keys for total daily notifications and total letters sent if letters are cancelled.
The new method is consistent with the others by keeping the `raise_exception` flag even though this may not be used.

Add `decrby` method to RedisClient

---

notifications_utils/request_helper.py
tests/test_request_id.py

https://trello.com/c/n4FmWuff/585-annotate-logs-with-cloudfront-http-request-ids
Firstly look for alternate headers `NOTIFY_TRACE_ID_ALT_HEADERS` (default cloudfront's and the ALB's), then failing that generate a random trace id.
Add similar configurability for span id headers and parent span id headers - this makes the code more symmetrical, even if we don't use the configuration options now.
Add a `get_onwards_request_headers` method which can be used by internal api clients etc. when preparing to make onwards requests. it will automatically handle the advance of `span_id` and `parent_span_id` correctly.
FWIW taking a cloudfront or ALB request id and passing it around as a `X-B3-TraceId` is strictly not zipkin compliant (because zipkin nowdays stipulates it wants a hexadecimal identifer …

NotifyRequest: handle trace ids when not handed `X-B3-TraceId` by paas

---

CHANGELOG.md
notifications_utils/logging.py
notifications_utils/version.py
tests/test_logging.py

https://trello.com/c/n4FmWuff/585-annotate-logs-with-cloudfront-http-request-ids
`parent_span_id` only needs to be present on one log of a span to be useful, but `span_id` needs to be present on all to identify which span each message comes from.

Add `span_id` and `parent_span_id` annotation to logs

---

notifications_utils/clients/antivirus/antivirus_client.py
notifications_utils/version.py
tests/clients/antivirus/test_antivirus_client.py

https://trello.com/c/n4FmWuff/585-annotate-logs-with-cloudfront-http-request-ids
Who knew that beyond https://github.com/alphagov/document-download-api/blob/main/app/utils/antivirus.py we also have an `AntivirusClient` in here.

AntivirusClient: include onwards request headers in outgoing requests

---

CHANGELOG.md
notifications_utils/request_helper.py
notifications_utils/version.py
tests/test_request_id.py

https://trello.com/c/n4FmWuff/585-annotate-logs-with-cloudfront-http-request-ids
This is me correcting some of my own logic from a few years ago.
The worry about such a `span_id` being propagated indefinitely is partially valid, but on balance it's probably worse not having *any* span id for the initial span as it makes it harder to find logs and failing to pass on a parent span id to the next server is indistinguishable from the mechanism being broken. And on a platform that isn't using a span id-aware router between apps, we should just handle the advancing of span ids ourselves.
When generating own `span_id`, prefix it with `self-` in attempt to avoid people going looking for whatever caller assigned it this span id. This is technically not a zipkin-compliant value, but we're already …

NotifyRequest: generate own `span_id` if none provided in headers

---

CHANGELOG.md
notifications_utils/jinja_templates/letter_pdf/_print_only_add_tag_css.jinja2
notifications_utils/jinja_templates/letter_pdf/_print_only_hide_barcodes_css.jinja2
notifications_utils/jinja_templates/letter_pdf/print.jinja2
notifications_utils/version.py
tests/test_template_types.py

Always hide barcodes when printing a letter
We used to only hide them on a page with Notify tag, but that
lead to a problem with bilingual letters when on first page of
English version of the letter barcodes were visible and were causing
problems for DVLA.

Fix barcodes bilingual letters

---

CHANGELOG.md
notifications_utils/logging.py
notifications_utils/version.py

https://trello.com/c/q5ehwcty/628-try-and-get-full-celery-logs-for-the-paas-into-logit
We're currently missing useful logs unless we keep all stderr from celery workers, but:
- we don't on paas
- it's horrible and unstructured, so it would be better if we didn't on ecs either
Adding `celery.redirected` should include messages that have been crudely structured from raw stdout/stderr messages, which we'll need because some important messages e.g. from kombu are sent through raw `print` calls.
I have tested this (minimally - it's hard to convince it to emit the right log messages from within celery) with the `notify-delivery-worker-sender`.

logging: also attach handlers etc. to `celery.worker` and `celery.redirected`

---

CHANGELOG.md
notifications_utils/logging.py
notifications_utils/version.py

Quick fix to prevent us logging some potentially sensitive information.

logging: set `celery.worker.strategy` logging to `WARNING`

---

CHANGELOG.md
notifications_utils/logging.py
notifications_utils/version.py
tests/test_logging.py

What
----
- Add option to change set of web paths to debug request logging for successful calls. Defaults to /_status and /metrics.
- Add new fields to log messages:
- user_agent
- host
- path
Why
----
- Our logs get too many successful status and metrics calls. This will remove them from our logs.
- Additional fields will help produce more useful logit dashboards.

Add option to ignore list of web paths from request logging

---

CHANGELOG.md
notifications_utils/logging.py
notifications_utils/version.py

It can return when we have more certainty over what values it will log or can rule out that it is ever given sensitive values.

logging: remove `celery.*` structured logging for now

---

CHANGELOG.md
notifications_utils/jinja_templates/email_template.jinja2

Do not merge until monday the 19th.
This also has three styling changes to align the GOVUK with the crown better.
Before
After

Update crown for email template

---

CHANGELOG.md
notifications_utils/recipients.py
notifications_utils/version.py
tests/test_recipient_validation.py

When a dash is used as to separate clauses our style is to use an en dash. Hyphens should only be used to join words.

Fix hyphen used as dash in phone validation error

---

CHANGELOG.md
notifications_utils/gunicorn_defaults.py
notifications_utils/version.py

gunicorn_defaults: don't set `statsd_host` in defaults

---

CHANGELOG.md
notifications_utils/logging/__init__.py
notifications_utils/version.py
tests/conftest.py
tests/test_logging.py

This sits on top of #1108 so the diff will be confusing till that is merged.
https://trello.com/c/kuPbusFR/724-check-if-we-should-and-then-remove-notifyruntimeplatform-functionality
`NOTIFY_RUNTIME_PLATFORM` was only used in one remaining place, and now it's effectively always set to "ecs". If we ever did want to reintroduce something similar, I think we're agreed we'd want to use a set of more explicit configuration parameters instead.
This also means there are no more cases where `NOTIFY_LOG_PATH` needs to do anything - we no longer use the aws logs agent - so references to it have also been removed.

logging: remove use of `NOTIFY_RUNTIME_PLATFORM` & `NOTIFY_LOG_PATH` config parameters

---

CHANGELOG.md
notifications_utils/postal_address.py
notifications_utils/version.py
tests/test_postal_address.py

> Gibraltar Post is currently developing a postcode system based on
> United Kingdom of Great Britain and Northern Ireland postcode system.
>
> For the time being, mailers are kindly requested to use GX11 1AA as
> generic postcode for Gibraltar
https://www.upu.int/UPU/media/upu/PostalEntitiesFiles/addressingUnit/gibEn.pdf
While Gibraltar is a British Overseas Territory it’s considered to be in ‘Europe Zone 3’ according to Royal Mail:
https://www.royalmail.com/sending/international/country-guides#accordion-item-11113
We’ve also confirmed with DVLA that they would:
- treat mail addressesed to Gibraltar as international
- reject mail addressed UK-style address (postcode only) to Gibraltar
Therefore we have 2 options:
1. normalise `GX11 1AA` to `Gibraltar`
2. reject addresses that end in …

Reject Gibraltar’s postcode

---

.git-blame-ignore-revs
.pre-commit-config.yaml
CHANGELOG.md
notifications_utils/clients/antivirus/antivirus_client.py
notifications_utils/field.py
notifications_utils/insensitive_dict.py
notifications_utils/serialised_model.py
notifications_utils/version.py
pyproject.toml
requirements_for_test.txt
setup.py

our versions of black and ruff are a bit out of date and it was causing havoc with my editor - lets bump them. there's also an outsanding CVE in black `>= 0, < 24.3.0` - https://github.com/advisories/GHSA-fj7x-q9j7-g6q6
if people are happy with this i'll upgrade them all in the rest of our repos

Bump linters

---

CHANGELOG.md
notifications_utils/clients/zendesk/zendesk_client.py
notifications_utils/version.py
tests/clients/zendesk/test_zendesk_client.py

We are switching to use a new Zendesk form, so this changes the Zendesk
client. We now need to pass in the ID of the new form, and instead of
populating the "Ticket category" dropdown we want to populate a dropdown
called "Task type". This will only ever have one thing selected, so
doesn't need to be able to take a list of values.

Update Zendesk client for new form

---

CHANGELOG.md
notifications_utils/recipients.py
notifications_utils/version.py
notifications_utils/version_tools.py
pyproject.toml
scripts/bump_version.py
tests/clients/redis/test_redis_client.py
tests/test_logging.py
tests/test_sanitise_text.py

This will let us share linter config between the apps. In the future it might even let us share common dependencies between the apps, since `pyproject.toml` can do dependency management.
This will require adding a `make` command to each app like:
```bash
python -c "from notifications_utils.version_tools import copy_pyproject_toml; copy_pyproject_toml()"
```
It also updates a couple of bits of config in `pyproject.toml` so that we’ll have parity when we drop this into the admin app.

Add a command to copy `pyproject.toml` into apps

---

CHANGELOG.md
notifications_utils/clients/redis/request_cache.py
notifications_utils/version.py
tests/clients/redis/test_request_cache.py

For context, when the admin app wants to get data from our API
it will first try and get the data from redis and if the data
doesn't exist in redis, it will get the data from the API and then
finish by setting that data in redis. When the admin app wants to
update data for our API, it currently calls out to the API to
update the data and then deletes any existing/relevant data cached
in redis. The subsequent time it tries to get this data that it just
updated, it will use the usual approach for getting data that will
set the redis key too.
There is a problem with when the admin app wants to update something
in the database. At the moment, it will start by calling the API
to update the database and if that is successful it will then attempt
to delete the relevant cache keys in redis. But …

Ensure no stale data in redis if redis errors when deleting cache key

---

CHANGELOG.md
notifications_utils/clients/zendesk/zendesk_client.py
notifications_utils/version.py
tests/clients/zendesk/test_zendesk_client.py

In order to update a ticket, you need to know its ID. This returns the
ticket ID from the `send_ticket_to_zendesk` method so that we can update
a ticket immediately after creating it. We want to start adding an
internal note if a user who is not logged in creates a ticket.

Return Zendesk ticket ID when creating a ticket

---

CHANGELOG.md
notifications_utils/version.py
notifications_utils/version_tools.py
requirements_for_test.txt
requirements_for_test_common.txt
setup.py

This will let us:
- remove more dependencies from each app’s requirements files
- share common config for pre-commit hooks, rather than having to manually maintain and update one in each app

Put more common configuration and dependencies in `notifications-utils`

---

CHANGELOG.md
notifications_utils/version.py
setup.py

The API has the Gunicorn version pinned here:
https://github.com/alphagov/notifications-api/blob/e175f90d8f56c4a1190f2c29dfa1954ff6b87e64/requirements.in#L13
This resolves to version 20.1.0 here:
https://github.com/benoitc/gunicorn/blob/1299ea9e967a61ae2edebe191082fd169b864c64/gunicorn/__init__.py#L6C16-L6C26
So to avoid a dependency conflict we need to reduce the required version to a common baseline in this repo.

Reduce minimum required version of Gunicorn

---

CHANGELOG.md
notifications_utils/recipient_validation/errors.py
notifications_utils/recipient_validation/phone_number.py
notifications_utils/version.py
tests/recipient_validation/test_phone_number.py

https://trello.com/c/I67noSbf/10-update-phone-number-validation-to-optionally-allow-uk-landlines
More refactoring of `InvalidPhoneError` ahead of adding UK landlines.
This one's quite a big one - I'm taking an opinionated stance that rather than writing code like `raise InvalidPhoneError('some error message')`, it's nicer to write `raise InvalidPhoneError(code=InvalidPhoneError.Codes.SOME_ERROR)`. Then, the exception class itself has a list of all the error codes, and a list of all the human-readable messages for surfacing on the front-end etc.
This means we can define these messages once, and only need to surface them at exit points (API error json serialisation, form rendering) and can just use the codes if we need to branch.
We're not doing work on the API v2 error slugs just yet but …

Invalid phone error refactor

---

CHANGELOG.md
notifications_utils/recipient_validation/errors.py
notifications_utils/recipient_validation/phone_number.py
notifications_utils/version.py
tests/recipient_validation/test_phone_number.py

https://trello.com/c/I67noSbf/10-update-phone-number-validation-to-optionally-allow-uk-landlines
🚨 This PR is targeting invalid-phone-error-refactor for a simpler diff 🚨 
Adds a new function for UK landline validation. Instead of hand-writing more code, instead we can lean on google's [`libphonenumber`](https://github.com/google/libphonenumber), which we already have as a dependency anyway.
we already use phonenumbers in `format_phone_number_human_readable` as it nicely formats numbers. It has a whole suite of validation features too.
We often find other teams asking us how we validate phone numbers so they can replicate it on their own frontend. We link to this repo but it would be much nicer if we could just point them to a well supported third party library with a variety of …

Phone number validation

---

notifications_utils/recipient_validation/phone_number.py
notifications_utils/version.py
tests/recipient_validation/test_phone_number.py

Adds validation logic allowing UK mobile numbers reserved by OFCOM for use in TV and Radio dramas, as these are (correctly) considered in valid by the `phonenumbers` library.
This fix prevents a number of unit tests in notifications-api from failing (as they use TV numbers in their testing).

Bug fix to allow validation of UK mobile "TV numbers"

---

CHANGELOG.md
notifications_utils/recipient_validation/postal_address.py
notifications_utils/version.py
tests/recipient_validation/test_postal_address.py

The `has_no_fixed_abode_address` method checks that no address lines
simply consist of "NFA" or "NFA," and that "no fixed address" or "no
fixed abode" is not in the address (all case insensitive). Letters sent
to no fixed abode addresses have been causing issues since they often
contain invalid addresses and weren't intended to be sent.

Add validation for fixed abode addresses to `PostalAddress`

---

CHANGELOG.md
notifications_utils/logging/__init__.py
notifications_utils/version.py
tests/test_logging.py

[Trello](https://trello.com/c/JKMlpumI/835-include-payload-size-of-post-request-on-logs)
What
----
Add new request log fields.
- environment_name: Name of the notify environment
- request_size: POST/PUT data size
- response_size: http response size
Why
----
We now share some logit environments across multiple environments. In order to separate requests we need the environment name.
During incidents it is useful to get an idea of the request size being uploads as well as the response size.

Add new request log fields

---

CHANGELOG.md
notifications_utils/version.py
notifications_utils/version_tools.py

Not all of our repos freeze their requirements from a `requirements.in` file into a `requirements.txt` file.
Some have only a `requirements.txt` file which is edited directly.
So our version script should write to that instead, if it can’t find a `requirements.in` file.

Write to `requirements.txt` if `requirements.in` doesn’t exist

---

CHANGELOG.md
notifications_utils/template.py
notifications_utils/version.py
tests/test_template_types.py

We have started sending `list-unsubscribe` headers if a user marks a template as unsubscribeable, for teams who aren’t using the API.
However we are already telling these teams to add unsubscribe links to the body of their emails.
This means:
- there are two different ways to add unsubscribe links
- user will have to manage requests to unsubscribe coming from two different places
This will be confusing, and make it harder for us to write good guidance that users will be able to follow, and harder to explain what the ‘let users unsubscribe from these emails’ checkbox does.
If we have a confusing product proposition and users cant follow our guidance then we risk our spam score rising.
This commit adds a way to insert an unsubscribe link (which we will generate) to the footer of every …

Add `unsubscribe_link` argument to email templates

---

CHANGELOG.md
notifications_utils/recipient_validation/phone_number.py
notifications_utils/version.py
tests/recipient_validation/test_phone_number.py

Separate out check for if service can't send to international but tries to
When this check was happening with all the rest of the number validation, when it failed we re-run it with a throoghly normalised number, which made phonenumbers libary think it's a UK landline that's too long for US numbers.
When we do it separately, we raise the NOT_A_UK_MOBILE error as we should, and we don't try to overnormalise when we get it.

Fix validation error for international numbers for services without international permissions

---

CHANGELOG.md
notifications_utils/recipient_validation/phone_number.py
notifications_utils/version.py
tests/recipient_validation/test_phone_number.py

Premium rate numbers are a known vector of attack. This updates the phonenumber validation code to raise an exception and fail if a service tries to create an sms notification destined for a premium rate number.

disallow premium numbers when validating

---

CHANGELOG.md
notifications_utils/international_billing_rates.yml
notifications_utils/version.py
tests/test_international_billing_rates.py

This adds the following to `international_billing_rates.yml` so that we can send SMS to them:
* Eritrea
* Wallis and Futuna
* Niue
* Kiribati
* Tokelau

Add new areas to international billing rates

---

CHANGELOG.md
notifications_utils/recipients.py
notifications_utils/version.py
tests/test_recipient_csv.py

updates RecipientsCSV to use new validation code for services with sms_to_uk_landlines enabled
CSV validation currently fails on admin if a csv file contains a valid UK landline number. This update will let us add the required logic to admin, to validate against the latest validation code which allows UK landlines for services with this feature enabled

RecipientsCSV validates UK landlines for services with sms_to_uk_landlines enabled

---

CHANGELOG.md
notifications_utils/local_vars.py
notifications_utils/version.py
tests/test_local_vars.py

Distant yak-shave ultimately for https://trello.com/c/ORGrd1jn/498-upgrade-docker-images-for-our-ecs-apps-to-debian-bookworm
The intention is to use this in apps where we need to move from (ab)using globals to context/thread-local pseudo-globals. This is because some of those resources currently referenced through globals need changes that will make them thread-unsafe, and it's cleaner pushing the thread-safety concerns out of those resources than internalizing it.

add `LazyLocalGetter` and tests

---

CHANGELOG.md
README.md
notifications_utils/recipient_validation/phone_number.py
notifications_utils/version.py
tests/recipient_validation/test_phone_number.py

Adds validation check to PhoneNumber so that the error `TOO_SHORT` is raised if an empty string is passed into the object as a phone number
Users of the v2 api expect, and often require, consistent error messages to be returned from the API as their code often does comparisons against errors as strings to handle notify errors. In the case of empty strings, an error corresponding to InvalidPhoneError.Codes.TOO_SHORT is expected

Empty strings for phone numbers return "TOO_SHORT" error message

---

CHANGELOG.md
notifications_utils/local_vars.py
notifications_utils/version.py

On the long road to https://trello.com/c/ORGrd1jn/498-upgrade-docker-images-for-our-ecs-apps-to-debian-bookworm
Because of the odd way the `api` app (at least) uses its api clients it becomes useful to be able to see a `LazyLocalGetter`'s inner type without populating it.
But to ensure this information is never *wrong* expose this as an _enforced_ `expected_type` mechanism.
~Also add `LazyLocalGetterResetter` which is (in this iteration) just a simple wrapper around a list that allows all the registered `LazyLocalGetter`s to be reset in a single call.~

`LazyLocalGetter` improvements

---

CHANGELOG.md
notifications_utils/clients/antivirus/antivirus_client.py
notifications_utils/clients/zendesk/zendesk_client.py
notifications_utils/version.py
tests/clients/antivirus/test_antivirus_client.py
tests/clients/zendesk/test_zendesk_client.py

On the long road to https://trello.com/c/ORGrd1jn/498-upgrade-docker-images-for-our-ecs-apps-to-debian-bookworm
This is a breaking change as it effectively makes these clients non-thread-safe. But it's better to declare them as non-thread-safe and only expect each to be used from one thread than to push all the complexity of managing different contexts into each class.

AntivirusClient, ZendeskClient: use persistent requests sessions

---

CHANGELOG.md
notifications_utils/version.py
setup.py
tests/recipient_validation/test_phone_number.py

It was discovered that a subset of valid Jersey phone numbers were being incorrectly invalidated by the phone_numbers library code due to a bug in the regex phone numbers were being validated against for the Jersey region. This new code provides a fix

Updates phone_numbers library to 8.13.45 to fix a validation bug with certain Jersey phone numbers

---

CHANGELOG.md
notifications_utils/clients/antivirus/antivirus_client.py
notifications_utils/clients/zendesk/zendesk_client.py
notifications_utils/version.py
tests/clients/antivirus/test_antivirus_client.py
tests/clients/zendesk/test_zendesk_client.py

This reverts the API client changes merged in  #1145 because we need  #1149 to make it out to apps quickly

Revert API client changes

---

.pre-commit-config.yaml
CHANGELOG.md
notifications_utils/version.py
requirements_for_test_common.txt
tests/test_logging.py

Mainly doing this because the output of Pytest is much nicer in version 8 (see below). But I figure it can’t hurt to get bug fixes and improvements from the other dependencies too.

Bump test requirements to the latest versions

---

CHANGELOG.md
notifications_utils/recipient_validation/postal_address.py
notifications_utils/version.py
tests/recipient_validation/test_postal_address.py

This postcode hasn’t been used for a while:
> GIR 0AA […] is the traditional Postcode of Girobank, now part of the Santander group. This Postcode appears on the Postzon product but not on PAF® nor on other raw data products. 
– https://www.poweredbypaf.com/wp-content/uploads/2017/07/Latest-Programmers_guide_Edition-7-Version-6.pdf (2017)
If a postcode isn’t in PAF then it isn’t addressable so we shouldn’t try to send letters to it, and by removing it we can make our code a bit simpler.

Drop Girobank’s postcode from validation

---

CHANGELOG.md
notifications_utils/clients/zendesk/zendesk_client.py
notifications_utils/version.py
tests/clients/zendesk/test_zendesk_client.py

The Zendesk client now takes an optional argument called `user_created_date`. If provided, this value is used to populate a new field we have on the form which is a calendar date picker. This will let us analyse how long the people opening tickets have been using Notify for.

Update Zendesk client to add a new optional argument for the date a user was created

---

notifications_utils/version_tools.py

A new version of utils might have introduced new requirements, or new linter options. So to keep the config in sync with the version of utils specified in the requirements file we should automatically check for new config files every time we bump the version in an app.

Automatically copy config after version bump

---

.pre-commit-config.yaml
CHANGELOG.md
notifications_utils/version.py
requirements_for_test_common.txt

This reverts commit d72195a650ec4cd63a689a1d6c57cd0c599a4398.
These new versions were not compatible with existing dependencies in the API

Revert "Bump test requirements to the latest versions"

---

CHANGELOG.md
notifications_utils/serialised_model.py
notifications_utils/version.py
tests/test_serialised_model.py

Upstreams the work from https://github.com/alphagov/notifications-admin/pull/5210
```python
class User:
ALLOWED_PROPERTIES = {"name"}
```
```python
class User:
name: str
```

Rewrite `SerialisedModel` to use annotations

---

CHANGELOG.md
notifications_utils/recipient_validation/phone_number.py
notifications_utils/recipients.py
notifications_utils/version.py
tests/recipient_validation/test_phone_number.py

The default behaviour of `notifications_utils.recipient_validation.phone_number.PhoneNumber` validates landline numbers. We want to be able to toggle this on or off _via_ a constructor argument so that this code can be used to validate phone numbers for **all** services, not just those with the `sms_to_uk_landline` permission.
This change adds the constructor argument `allow_landline` and makes changes to the validation code to throw an exception if a valid landline is passed when `allow_landline=False`.

Add allow landline flag

---

CHANGELOG.md
notifications_utils/asset_fingerprinter.py
notifications_utils/version.py
tests/test_asset_fingerprinter.py

So we can share it between our frontend apps.
This continues its journey, having been:
- introduced here: https://github.com/Crown-Commercial-Service/digitalmarketplace-buyer-frontend/pull/111
- refactored into shared code here: https://github.com/Crown-Commercial-Service/digitalmarketplace-utils/pull/102
- copied into Notify here: https://github.com/alphagov/notifications-admin/pull/171 (“They have it in a shared codebase, we only have one frontend app so don’t need to do that.”)
- copied into Document Download here: https://github.com/alphagov/document-download-frontend/pull/1

Migrate `AssetFingerprinter` into utils

---

CHANGELOG.md
notifications_utils/clients/antivirus/antivirus_client.py
notifications_utils/clients/zendesk/zendesk_client.py
notifications_utils/version.py
tests/clients/antivirus/test_antivirus_client.py
tests/clients/zendesk/test_zendesk_client.py

#1145 was reverted in #1150 because not all apps were ready to be switched to them.
But we do need those changes for the long road to https://trello.com/c/ORGrd1jn/498-upgrade-docker-images-for-our-ecs-apps-to-debian-bookworm

Reintroduce API client changes from 83.0.0

---

CHANGELOG.md
notifications_utils/logging/__init__.py
notifications_utils/version.py
tests/test_logging.py

Adding this (useful) field to the logs causes the response to be eagerly consumed in an attempt to calculate the final length, which negates the point of streaming responses. This may be why we observed our streaming responses apparently "not working" recently.
However simply making them skip the calculation for streaming responses does change behaviour - it means `after_request` logs are now emitted when we return the response status and headers. Which would leave us with no visibility of when the streamed request "ended". So this also adds a new log message for streamed responses being "closed".
Unfortunately from what I can see, flask/werkzeug doesn't really keep a tally of bytes returned in streamed responses, so it's not trivially possible to include a "final" response size in this …

logging: don't `calculate_content_length()` for `after_request` logs of streaming responses

---

CHANGELOG.md
notifications_utils/template.py
notifications_utils/version.py
tests/test_recipient_csv.py
tests/test_template_types.py

The only thing using it was the admin app and we moved the code into notifications-admin in https://github.com/alphagov/notifications-admin/pull/5266

Remove EmailPreviewTemplate

---

CHANGELOG.md
notifications_utils/logging/__init__.py
notifications_utils/version.py

We aren't in app context when this is called by a real wsgi server.

logging: don't use `current_app` in `_log_response_closed`

---

CHANGELOG.md
notifications_utils/logging/__init__.py
notifications_utils/version.py
tests/test_logging.py

See commit messages for more information.
This is to address fields like `request_id` not being available on the streaming-response-closed log message due to not being in a request context at the time of generation.
Not pretty, but blame flask/werkzeug's damn silly context system.

logging: refactor filters to fall back to provided record fields if app context not available

---

CHANGELOG.md
notifications_utils/version.py
setup.py

to metadata that was causing some ugandan numbers to fail in error.

Bug Fix: Updates PhoneNumbers to 8.13.48 to apply fix

---

CHANGELOG.md
notifications_utils/version.py
notifications_utils/version_tools.py

currently, it just returns whatever is at the URL (for example an error page). We saw problems on concourse where it just wrote an error page to a requirements_common file and then just tried to carry on happily

raise an exception if we cant fetch from github

---

CHANGELOG.md
notifications_utils/version.py
notifications_utils/version_tools/__init__.py

This might have solved our issues with version_tools without changing to importlib - but it was probs a good idea to do that anyway.
This'll fix some issues i ran into with the bump-utils script that the other repos run though

Use github api when fetching files from github

---

CHANGELOG.md
notifications_utils/formatters.py
notifications_utils/recipients.py
notifications_utils/version.py
tests/test_recipient_csv.py

We were stripping leading commas from the CSV data.
This mean that a file which looks like
```CSV
,,,phone number
,,,07900900123
```
1| | | phone number
-|-|-|-
2| | | 07900900123
Got turned into
```CSV
phone number
,,,07900900123
```
1| phone number | |&#9;
-|-|-|-
2| | | 07900900123
This meant that the `phone number` header and the phone number itself were no longer in the same column, causing an unexpected error.
We still want to strip commas from the end of the file, in order to remove any completely empty rows.

Allow leading empty columns in CSV files

---

notifications_utils/version.py
setup.py

2.32.0 and 2.32.1 were yanked due to issues with CVE-2024-35195[^1], so lets make sure we require newer versions
[^1]: https://pypi.org/project/requests/2.32.1/#history

bump requests

---

CHANGELOG.md
notifications_utils/international_billing_rates.py
notifications_utils/recipient_validation/phone_number.py
notifications_utils/version.py
tests/recipient_validation/test_phone_number.py

if you parse the phone number "24741111", the parser doesn't know if it's international, so starts off assuming it has a country code of +44.  Then, as that number isn't a valid UK number, we'd go down the "forced_international_number" route - and stick a plus on the beginning and parse again. This would prompt phonenumbers to realise it's not a UK phone number but actually one from the Ascension Island - and in fact is a valid number there.
The problem is that we don't support Ascension Island. However, the unsupported country code check takes place before the forced international code branch - and compares against the assumed "+44" code.
This led to a bug where the phone number appeared valid, but if you tried to call `get_international_phone_info` it would KeyError when trying to find …

Fix ascension island bug

---

CHANGELOG.md
notifications_utils/version.py
notifications_utils/version_tools/__init__.py

This reverts commit https://github.com/alphagov/notifications-utils/commit/484d4530885448ef4a61ce811bcefa015bc3e941.
We now do this as part of the freeze-requirements step in the repos.
Also because the script now pulls the config files from the local install (not over the network) the files it will be pulling will be out of date at this point (before installing the new utils version).

Revert "Automatically copy config after version bump

---

CHANGELOG.md
notifications_utils/formatters.py
notifications_utils/version.py
tests/test_template_types.py

You can bypass newline truncation<sup>1</sup> by sending the dreaded unicode ‘hangul filler’ character<sup>2</sup> in my personalisation.
This could be utilised by a dodgy character who wants to hide some portion of the email content (if, say, they've utilised template injection to create a phishing email)
***
Fixes #1119
***
1. Defined at https://github.com/alphagov/notifications-utils/blob/88c57d5eb530b88794814e57249c2403227aa664/notifications_utils/markdown.py#L222
2. https://unicode-explorer.com/c/3164

Remove hangul filler character from emails

---

CHANGELOG.md
notifications_utils/international_billing_rates.py
notifications_utils/recipient_validation/errors.py
notifications_utils/recipient_validation/phone_number.py
notifications_utils/recipients.py
notifications_utils/version.py
setup.py
tests/recipient_validation/test_phone_number.py
tests/test_international_billing_rates.py
tests/test_recipient_csv.py
tests/test_recipient_validation.py

Temporarily revert the removal of the old phone number validation code while decisions over how to safely incorporate the changes into api and admin are made
This reverts commit 21700ccc4f7ab841a7535664a0d0bef064934e10, reversing changes made to febec8ef3a90685a056fa8706a8df54d9ed044da.

Revert "Merge pull request #1158 from alphagov/remove-old-phonenumber validation"

---

CHANGELOG.md
notifications_utils/version.py
setup.py

We can’t upgrade all apps until https://github.com/psf/requests/issues/6730 is fixed (it stops the API from talking to DVLA)

Downgrade minimum version of requests to 2.32.3

---

CHANGELOG.md
notifications_utils/clients/redis/request_cache.py
notifications_utils/version.py
tests/clients/redis/test_request_cache.py

Returning a `CacheResultWrapper` from a `RequestCache.set`-wrapped function allows the function to contextually decide whether the result should be cached.
Internally this uses `functools.singledispatch` to detect `CacheResultWrapper` instances, so should allow further customization if the design of `CacheResultWrapper` isn't convenient for some situation.

`RequestCache`: add `CacheResultWrapper` to allow dynamic cache decisions

---

CHANGELOG.md
notifications_utils/version.py
setup.py

This fixes a couple of moderate security vulnerabilities.
Have tested locally against the admin app and there’s no breakages.

Bump minimum jinja2 version to latest

---

CHANGELOG.md
notifications_utils/logging/flask.py
notifications_utils/version.py
tests/test_logging.py

This allows the handler's log level to be set differently from `NOTIFY_LOG_LEVEL`, but it should continue to fall back to `NOTIFY_LOG_LEVEL`'s value if not set explicitly.
This is a stopgap workaround to introduce a little bit of flexibility into our weirdly inflexible log setup (i.e. to make it possible to get some use out of `NOTIFY_REQUEST_LOG_LEVEL` without having to raise the global log level.

flask logging: add `NOTIFY_LOG_LEVEL_HANDLERS` config variable

---

CHANGELOG.md
notifications_utils/eventlet.py
notifications_utils/logging/flask.py
notifications_utils/version.py

This will emit the raw values of the thread_time and perf_counter for the eventlet hub greenlet and, if the server greenlet has been helpfully annotated on to the flask application, that too.
These values aren't very useful on their own but cpu usage can inferred from the difference between successive calls.

logging: add verbose eventlet context if `request_time` is over a threshold

---

CHANGELOG.md
notifications_utils/version.py
pyproject.toml

When someone tries to access this file from the Github API it doesn’t cleanly redirect.
This is causing an error with what uv is trying to do in https://github.com/astral-sh/uv/pull/10765
We can do some work later to make sure these 2 files don’t get out of sync, or some other longer-term fix.

Don’t symlink pyproject.toml

---

CHANGELOG.md
Makefile
notifications_utils/formatters.py
notifications_utils/letter_timings.py
notifications_utils/recipients.py
notifications_utils/sanitise_text.py
notifications_utils/version.py
notifications_utils/version_tools/.pre-commit-config.yaml
notifications_utils/version_tools/requirements_for_test_common.in
notifications_utils/version_tools/ruff.toml
pyproject.toml
requirements_for_test.txt
tests/recipient_validation/test_phone_number.py
tests/recipient_validation/test_postal_address.py
tests/test_celery.py
tests/test_field.py
tests/test_formatters.py
tests/test_recipient_csv.py
tests/test_sanitise_text.py
tests/test_serialised_model.py
tests/test_template_types.py

It’s faster and means we have one fewer dependencies.
While ruff aims for 99.9% compatibility with black our codebase is big enough to hit a couple of the differences, hence some slight changes to Python code, and the need to consider this a breaking change for consuming apps.

Replace `black` with `ruff format`

---

CHANGELOG.md
MANIFEST.in
notifications_utils/version.py

Otherwise consuming apps won’t have access to it

Add `ruff.toml` to `MANIFEST.in`

---

notifications_utils/__init__.py

The specific motivation is our use of `gunicorn_defaults` from apps' `gunicorn_config.py`, which is evaluated before eventlet monkeypatching.

add comment to `__init__.py` suggesting people avoid additions

---

CHANGELOG.md
notifications_utils/recipient_validation/email_address.py
notifications_utils/version.py
notifications_utils/version_tools/ruff.toml
tests/test_asset_fingerprinter.py
tests/test_formatters.py
tests/test_markdown.py

Noticed this during a PR review and think it’s better to use a rule (where one exists) rather than a discussion back and forth.
> A noqa directive that no longer matches any diagnostic violations is likely included by mistake, and should be removed to avoid confusion.
– https://docs.astral.sh/ruff/rules/unused-noqa/

Add lint rule (RUF100) for inapplicable `# noqa`

---

CHANGELOG.md

If these are level 1 headings they get interpreted as comments in a commit message.
The version tools module expects a level 2 heading here:
https://github.com/alphagov/notifications-utils/blob/361486ff4960b5d02c162118b1fd64b097f9cb96/notifications_utils/version_tools/__init__.py#L84-L86

Fix heading levels in changelog

---

tests/test_celery.py

If we override methods in our subclass we should ensure they should have the same signature. This commit adds a test which checks for that.
`run` is an exception because it is dynamically created based on the function which the task will call.

Ensure `NotifyTask` is a polymorphic subclass of `Celery.Task`

---

CHANGELOG.md
notifications_utils/celery.py
notifications_utils/version.py
tests/test_celery.py

We [saw an error](https://govuk-notify-gds.sentry.io/issues/6332986034/?alert_rule_id=14332524&alert_timestamp=1740541085693&alert_type=email&environment=production&notification_uuid=0102d137-d24c-410c-9528-6171992721d0&project=4504949770092544&referrer=alert_email) when the `on_retry` method was called in production:
`make_task.<locals>.NotifyTask.on_retry() takes 5 positional arguments
but 6 were given`.
This updates the method to use the [same args as the Celery code](https://github.com/celery/celery/blob/e73b71ed2090e83765b14162cadde771c6b520ed/celery/app/task.py#L1048) specifies.

Update args for the `on_retry` method of `NotifyTask`

---

CHANGELOG.md
notifications_utils/insensitive_dict.py
notifications_utils/version.py
tests/test_insensitive_dict.py

I was surprised that `"first name" in InsensitiveSet(['firstname'])` evaluated to `False`.
This commit makes it work the way you’d expect.
We don’t use this in production code yet, but don’t think it can hurt.

Implement `InsensitiveSet.__contains__`

---

CHANGELOG.md
notifications_utils/jinja_templates/letter_pdf/preview.jinja2
notifications_utils/jinja_templates/letter_pdf/print.jinja2
notifications_utils/template.py
notifications_utils/version.py
tests/test_template_types.py

For bilingual letters, only show the barcodes on the Welsh first page, and not on the English first page - as this is how it will look when printed.
Review commit by commit.
Trello ticket: https://trello.com/c/Hr4MDKlM/152-barcodes-show-on-pages-after-the-1st-on-bilingual-letters
Related template-preview PR: https://github.com/alphagov/notifications-template-preview/pull/872
|BEFORE|AFTER|
|:---|:---|
|![Screenshot 2025-03-04 at 14 42 34](https://github.com/user-attachments/assets/a11fc90f-2c15-4043-b95f-0e6ecbaf763f)|![Screenshot 2025-03-04 at 14 39 39](https://github.com/user-attachments/assets/784bf017-121c-480b-a898-d52bccb6a4b3)|

[bug fix] Only show barcode on first page of letter preview

---

CHANGELOG.md
notifications_utils/markdown.py
notifications_utils/version.py
tests/test_markdown.py

QR codes in letters whose URL includes an ‘&' sign will have it encoded as the '&’ HTML entity. More details on [this card](https://trello.com/c/YESkaUO9/94-qr-codes-with-logos-in-have-encoded-as-amp). There is generic html escape which does not handle the URL use case. So when creating the QR code unescape html to get the original URL.

Fix qrcode with amp

---

CHANGELOG.md
notifications_utils/markdown.py
notifications_utils/version.py
tests/test_markdown.py

Addresses https://trello.com/c/7vrT4qfU/104-inset-text-sometimes-has-no-margin-bottom
To reliably have bottom margin applied across clients, bottom margin had to be moved to a wrapping div element.
**Before**
https://app.emailonacid.com/shared-preview/YNbYn8N9oO
**After**
https://app.emailonacid.com/shared-preview/IzCFf5SNC8

Fix inset text bottom margin in emails

---

CHANGELOG.md
notifications_utils/formatters.py
notifications_utils/version.py
tests/test_markdown.py

In https://github.com/alphagov/notifications-utils/pull/1204 we started prepending `http://` to any URLs which didn’t already have it, where those URLs were part of a Markdown link.
This didn’t account for URLs which use other protocols. Notably we have users who we’ve told to use `mailto:` links for managing unsubscriptions. This change broke those links by turning them into `http://mailto:…`
This commit fixes mailto links, and some other niche protocols which people may use.

Fix links with non-http protocols in Markdown URLs

---

CHANGELOG.md
notifications_utils/international_billing_rates.yml
notifications_utils/recipient_validation/phone_number.py
notifications_utils/version.py
tests/recipient_validation/test_phone_number.py
tests/test_international_billing_rates.py

The rate multipliers for international SMS are changing from 1 April
2025, so this change updates the yml file. The `+44` prefix has a rate
multiplier of 2 for Guersey, Jersey and the Isle of Man and 1 for
mainland UK, which requires a change in logic.

Update international SMS rate multipliers

---

tests/test_field.py

We’re going to be making some changes to this class as part of the unsafe placeholder work.
These tests make sure we don’t change existing behaviour which is currently undefined except by implementation.

Add more test cases for the `Field` class

---

pyproject.toml

`project.license` as a TOML table is deprecated
Seeing this warning locally:
> Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).
>
> By 2026-Feb-18, you need to update your project and remove deprecated calls or your builds will no longer be supported.
https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license
New format taken from https://spdx.org/licenses/

Use non-deprecated format for specifying project license

---

CHANGELOG.md
notifications_utils/celery.py
notifications_utils/version.py
tests/test_celery.py

This should partly address a some of the things I'm always moaning about - the lack of a logged identifier for a particular celery _task_ (the same request id is frequently applied en-masse to thousands of celery tasks) and the lack of a log message denoting the start of a celery task being processed (meaning if a worker dies we have no record of the task being partially executed).
This still isn't anywhere near as good as I'd like, where we'd extend span ids & parent span ids into celery task invocations, and any log message generated by a celery task would have this information annotated onto it.
Major bump to nudge people to mark their heavily called tasks with a reduced `early_log_level`
Tested a deployment on `-api`  via https://github.com/alphagov/notifications-api/pull/4425

celery.NotifyTask: add early-log messages, annotate end-of-task log messages with `celery_task_id`

---

CHANGELOG.md
notifications_utils/countries/data.py
notifications_utils/letter_timings.py
notifications_utils/version.py

- Extend `get_min_and_max_days_in_transit` to include economy transit 
- In [this Kick-off document](https://docs.google.com/document/d/12cZF-bnSk5TWgGi60Xf_qX3RZH1bEr-iGW56c8jIxjU/edit?tab=t.0#heading=h.emkr927lpq04), it says that the transit for Economy might take up to 6 days to be delivered and it is generally slower than 2nd Class. 
- Based on this, this function has been updated with a minimum of 2 days and max of 6 days for delivery
- [Allow postage to be economy in Notify](https://trello.com/c/Y95RhqNO/1244-allow-postage-to-be-economy-in-notify)

refactor: Extend utils to support economy mail

---

notifications_utils/field.py
tests/test_field.py
tests/test_placeholders.py

Best reviewed commit by commit.
Adds a placeholder of with the form `<my value>::unsafe>` that can be used to sanitise values that may contain vulnerable markdown syntax.
This will have the placeholder return a stub until later PRs can add the sanitisation logic. So, `str(Placeholder("((my name::unsafe)), {"my_name":"Richard"}))` is evaluated as `SANITISED` .

Extend Placeholder Syntax to include unsafe values

---

CHANGELOG.md
notifications_utils/s3.py
notifications_utils/version.py
tests/test_s3.py

Add multipart upload for large file handling. Implement full multipart upload lifecycle (create, upload, complete, abort).
Documentation here: https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-express-using-multipart-upload.html
This PR is part of the notifications request report data processing. Here is the [card](https://trello.com/c/sRiFZcNB/1197-function-report-data-processing) for more details.

Add s3 multipart upload

---

CHANGELOG.md
notifications_utils/recipients.py
notifications_utils/version.py
tests/test_recipient_csv.py

This is so that we can effectively check international sms message limit for jobs.

For `RecipientCSV` class, count international text messages

---

notifications_utils/logging/formatting.py

Silences this log message:
```
DeprecationWarning: pythonjsonlogger.jsonlogger has been moved to pythonjsonlogger.json
```

Reflect move of `pythonjsonlogger.jsonlogger`

---

CHANGELOG.md
notifications_utils/recipient_validation/phone_number.py
notifications_utils/recipients.py
notifications_utils/version.py
tests/test_recipient_csv.py

We still let services who don’t send international text messages send to the channel islands.
The rate limiting code considers these numbers international.
This means these services are blocked from sending to these numbers.
Looking at the phone numbers there’s no easy way for services to say which numbers are Channel Islands numbers. So it’s not reasonable for us to ask services to remove them from their data.
Instead we should not count them towards the rate limit.

Don’t count channel islands phone numbers against international rate limit

---

pyproject.toml

All our apps are using at least this version now, so that’s what we should test against in this repo.
The `requirements.txt` file already has this version:
https://github.com/alphagov/notifications-utils/blob/9154f4b5d0ff5d9ad212cb6f08b31297bdeeb63a/requirements_for_test.txt#L62
But changing it in `pyproject.toml` prevents backsliding.

Bump minimum Gunicorn version to 23

---

CHANGELOG.md
notifications_utils/recipients.py
notifications_utils/version.py
tests/test_recipient_csv.py

resolves an issue where if you had run out of international SMS for the day (or indeed, if we accidentally added to the cache limit for international SMS when you'd been sending other things like emails), we wouldn't let you send anything even if it wasn't an international SMS itself

Only consider SMS CSVs when checking international SMS limits

---

notifications_utils/recipient_validation/phone_number.py

Because:
- `self.number.country_code` returns `44` so would never match `+44`
- `44` is already in COUNTRY_PREFIXES from here: https://github.com/alphagov/notifications-utils/blob/73d5018cacd490863ca96544b059d63df07f2c3b/notifications_utils/international_billing_rates.yml#L240

Remove +44 from set of country codes

---

notifications_utils/recipient_validation/phone_number.py

We are using this method for rate limiting of international SMS, so it definitely shouldn’t be removed now

Remove outdated `TODO`

---

CHANGELOG.md
notifications_utils/celery.py
notifications_utils/version.py
tests/test_celery.py

Fixup for #1213. This is a misleading log message to emit as we're not an invocation of the stated celery task in this case.

`celery.NotifyTask`: don't emit early log if called synchronously

---

notifications_utils/field.py
tests/test_field.py
tests/test_markdown.py

Best reviewed commit by commit.
FIrst step of sanitising markdown syntax by escaping any markdown specific characters `*_(){}[]<>#+-.!| with a `\`

Unsafe placeholders sanitise markdown

---

notifications_utils/field.py
tests/test_field.py
tests/test_markdown.py
tests/test_placeholders.py

For the first iteration of sanitising placeholders we decide that if a replacement value contains a url, the entire value should be considered compromised and an empty string returned:

Remove urls from unsafe placeholders

---

CHANGELOG.md
notifications_utils/letter_timings.py
notifications_utils/version.py

- Update economy letter transit date to 5 days to be in line with expected delivery
- [Update delivery estimates code to accomodate economy postage](https://trello.com/c/JngKcHSO/1272-update-delivery-estimates-code-to-accomodate-economy-postage)

Refactor: Update economy transit date

---

notifications_utils/recipient_validation/phone_number.py

These are not used anywhere: https://github.com/search?q=org%3Aalphagov+CROWN_DEPENDENCY_RANGES&type=code
Instead we use libphonenumber to determine if a phone number is from one of the Crown Dependencies

Remove `CROWN_DEPENDENCY_RANGES`

---

.gitignore
CHANGELOG.md
notifications_utils/logging/celery.py
notifications_utils/version.py
tests/logging/dummy_celery_app.py
tests/logging/test_celery.py

https://trello.com/c/btX99C0D/1085-celery-workers-not-logging-critical-errors
What
----
- Remove the warnings override. Feels a bit dodgy. It only means we miss a few items on startup
- Allow celery beat and celery worker log levels to be specified independently and from our normal config setup. 
- Update tests to include celery beat log tests
- Add test to ensure we do not print celery worker log messages if log level is CRITICAL.
Why
----
Previous implementation lacked beat testing and was using a non-standard configuration

Celery Logging Update

---

CHANGELOG.md
notifications_utils/jinja_templates/email_template.jinja2
notifications_utils/template.py
notifications_utils/version.py

Adds the ability to turn on the new GOV.UK branding in emails we send with the GOV.UK branding[^1]
https://trello.com/c/tqglnJkB/1285-update-email-template-with-rebranded-govuk-logo
Reviewers should try sending an email with the `rebrand` keyword arg set to `True` and `False` in the API code (see [this branch on API](https://github.com/alphagov/notifications-api/compare/add-rebrand-switch-to-email-template-calls)). They should also check the email previews you can see when you change email branding in settings on Admin (see [this branch on Admin](https://github.com/alphagov/notifications-admin/compare/add-rebrand-switch-to-email-template-calls)). Please check the version of utils with these changes works:
- with the existing code in API and Admin
- with the addition of the `rebrand` arg, …

Update GOVUK logo to new brand (behind a flag)

---

notifications_utils/version.py

We've made breaking changes since 99.8.0 that won't be correctly tagged (and so importable) until version.py is bumped as well

major version bump to 100.0.0

---

CHANGELOG.md
notifications_utils/version.py
pyproject.toml
requirements_for_test.txt

Major version bump from 8.13.52 to 9.0.9. Looking at the release notes, I'm confident that this is not technically a breaking change for python. The phonenumbers python port of libphonenumber repsects the semantic versioning of the original java codebase.
The [release notes for v9.0.0](https://github.com/google/libphonenumber/releases/tag/v9.0.0) tell us that the major version bump is due to an update to java 8 from 1.7. This is not a breaking change for the python port.

Update phonenumbers 9.0.9

---

CHANGELOG.md
notifications_utils/logging/flask.py
notifications_utils/version.py
tests/test_logging.py

https://trello.com/c/CjPJrFAk/1160-notifications-api-recording-all-remoteaddr-as-internal-ips
What
----
Add x-forwarded-for info to log files.
Why
----
We want to log the ips we see at each stage of the request.

Add x-forwarded-for information to log files

---

CHANGELOG.md
notifications_utils/celery.py
notifications_utils/version.py
requirements_for_test.in
requirements_for_test.txt
tests/test_celery.py

This PR overrides celery's `_get_backend` method. This is is to help facilitate disabling celery's result backend as described in [this](https://trello.com/c/S1FTSLuT/346-disable-celery-result-backend-in-production) card.
Currently if `result_backend` is `None` celery.backend still calls `Celery._get_backend()` which scans for a result backend store. 
Profiling results have shown that this is a significant bottleneck as the scanning for a result backend occurs multiple times and uses significant resources.
In the PR `Celery._get_backend` is being overridden in `NotifyCelery` to prevent scanning for a result_backend if `result_backend` is None. Performance testing shows that this will lead to approximately 26% improvement in [performance](https://docs.google.com/document/d/1eQfwd-omuM9bIYLt …

Override celery get backend

---

CHANGELOG.md
docker/Dockerfile
notifications_utils/version.py
notifications_utils/version_tools/__init__.py
requirements_for_test.txt

This PR upgrades notifications-utils to Python 3.13.
Python 3.13 brings changes to the behaviour of locals() which necessitated a compensatory change to get_remote_version()

Upgrade to python313

---

CHANGELOG.md
notifications_utils/formatters.py
notifications_utils/version.py
tests/test_field.py
tests/test_formatters.py
tests/test_template_types.py

Looks like GMail and Outlook re-renders them literally as `&lpar;` rather than `(`.
This only happens when the user puts the entity in their content.
When we changed to support artibrary HTML entities in https://github.com/alphagov/notifications-utils/commit/e7886aa4e1daa8744262c8ee1469410543bff5c5 we kept parentheses as a special-case. This wasn’t necessary.
Probably still a good idea to special-case:
- ampersands (because URL query strings)
- non-breaking spaces (because maybe some clients might try to normalise unicode whitespace characters)
Before | After
---|---

Don’t encode parentheses as HTML entities in emails
